package dev.fardavide.oltre.core

// Generation is pure, O(1) per world, and reads nothing but the seed and the coordinate.
//
// Two properties are load-bearing and both are asserted by tests rather than left to good
// intentions:
//
// 1. **Locality.** `worldAt` answers for one coordinate without generating its neighbours, so the
//    Compose `Canvas` renders any viewport lazily and slice 5 never holds a galaxy in memory.
// 2. **Sub-stream stability.** Every axis is drawn from its *own* named stream, hashed from the
//    world's seed and an axis tag. So the galaxy generated by seed S today is the same galaxy under
//    seed S after the next three slices add fields to `World`. Draw a new axis off a shared
//    sequential stream instead and every future addition silently rerolls everyone's map —
//    `GalaxySubStreamTest` exists to fail loudly the moment someone does.
//
// Nothing here changes with time. `advance()` is untouched and **no hook is left for it**: in 0.2
// the galaxy is fixed the instant the seed is minted, and a speculative per-tick entry point would
// be a promise the design has not made. Surveying and ownership change through the save's galaxy
// state, not through the clock.

// SplitMix64's finalizer. Written out rather than taken from `kotlin.random.Random` because the map
// is part of the save format: a stdlib generator whose internals changed would silently reroll
// every installed player's galaxy, where these two constants cannot.
private const val MIX_A: Long = -0x40a7b892e31b1a47 // 0xBF58476D1CE4E5B9
private const val MIX_B: Long = -0x6b2fb644ecceee15 // 0x94D049BB133111EB

private fun mix(value: Long): Long {
    var z = value
    z = (z xor (z ushr 30)) * MIX_A
    z = (z xor (z ushr 27)) * MIX_B
    return z xor (z ushr 31)
}

// Odd, widely spaced multipliers so two coordinates that differ by one in different components
// cannot collide before the mix.
// Written as unsigned hex and converted, which is why these are `val` rather than `const val`: the
// recognisable constants are worth more to a reader than their two's-complement spellings.
private val GALAXY_SALT: Long = 0x9E3779B97F4A7C15uL.toLong()
private val SYSTEM_SALT: Long = 0xC2B2AE3D27D4EB4FuL.toLong()
private val SLOT_SALT: Long = 0x165667B19E3779F9uL.toLong()

// Successive draws inside one axis — the second hazard after the first. Never used to reach a
// *different* axis, which is the whole point of the tags below.
private val DRAW_STEP: Long = 0x27D4EB2F165667C5uL.toLong()

// One named stream per generated quantity. **Adding a constant here is free; reordering or reusing
// one is a save-format change**, because every existing seed would produce a different galaxy.
// A new trait in a later slice takes a new tag and shifts nothing that already exists.
internal enum class GenerationAxis(val tag: Long) {
    OCCUPANCY(0x1D8E4E27C47D124FuL.toLong()),
    STAR_CLASS(0x2545F4914F6CDD1DuL.toLong()),
    TEMPERATURE_JITTER(0x3C79AC492BA7B653uL.toLong()),
    GRAVITY(0x4F1BBCDD8E4E27C4uL.toLong()),
    PRESSURE(0x5851F42D4C957F2DuL.toLong()),
    HAZARDS(0x6A09E667F3BCC909uL.toLong()),
    RELAY(0x7F4A7C15F39CC060uL.toLong()),
    RELAY_SLOT(0x8EBC6AF09C88C6E3uL.toLong()),
    HOME(0x9E3779B97F4A7C55uL.toLong()),
}

// The system's own seed, shared by every slot in it — which is why the star class is the same for
// all of them. Deliberately the prefix of `worldSeed`: one hash chain, stopped a step earlier.
internal fun systemSeed(seed: GalaxySeed, galaxy: Int, system: Int): Long {
    var hash = mix(seed.value)
    hash = mix(hash + GALAXY_SALT * galaxy)
    return mix(hash + SYSTEM_SALT * system)
}

internal fun worldSeed(seed: GalaxySeed, at: GalaxyCoordinate): Long =
    mix(systemSeed(seed, at.galaxy, at.system) + SLOT_SALT * at.slot)

internal fun streamOf(baseSeed: Long, axis: GenerationAxis): Long = mix(baseSeed + axis.tag)

internal fun draw(stream: Long, index: Int): Long = mix(stream + DRAW_STEP * index)

// `mod` rather than `%` throughout: a hash is as often negative as positive, and `%` would make
// half the galaxy fall outside every range.
private fun Long.boundedBy(bound: Int): Int = mod(bound.toLong()).toInt()

internal fun uniformFrom(stream: Long): Uniform = Uniform(stream.boundedBy(Uniform.BASIS + 1))

internal fun percentFrom(stream: Long): Int = stream.boundedBy(100)

fun starClassAt(seed: GalaxySeed, galaxy: Int, system: Int): StarClass =
    GalaxyBalance.starClass(streamOf(systemSeed(seed, galaxy, system), GenerationAxis.STAR_CLASS).boundedBy(3))

// The entry point. Null when the slot is empty, which is most of them.
fun worldAt(seed: GalaxySeed, at: GalaxyCoordinate): World? {
    val world = worldSeed(seed, at)
    if (percentFrom(streamOf(world, GenerationAxis.OCCUPANCY)) >= GalaxyBalance.occupancyPercent(at.slot)) {
        return null
    }

    val starClass = starClassAt(seed, at.galaxy, at.system)
    val jitterSpan = 2 * GalaxyBalance.TEMPERATURE_JITTER + 1
    val jitter = streamOf(world, GenerationAxis.TEMPERATURE_JITTER).boundedBy(jitterSpan) -
        GalaxyBalance.TEMPERATURE_JITTER
    val temperature = GalaxyBalance.temperature(at.slot, starClass, jitter)
    val gravity = GalaxyBalance.gravity(uniformFrom(streamOf(world, GenerationAxis.GRAVITY)))
    val pressure = GalaxyBalance.pressure(uniformFrom(streamOf(world, GenerationAxis.PRESSURE)))

    return World(
        at = at,
        starClass = starClass,
        traits = WorldTraits(
            temperature = temperature,
            gravity = gravity,
            pressure = pressure,
            // Derived, never rolled — the pillar in three lines.
            metalRichness = GalaxyBalance.metalRichness(gravity),
            crystalRichness = GalaxyBalance.crystalRichness(pressure),
            deuteriumRichness = GalaxyBalance.deuteriumRichness(temperature),
            hazards = hazardsFrom(streamOf(world, GenerationAxis.HAZARDS)),
            fields = GalaxyBalance.fields(gravity),
        ),
    )
}

// 35% one hazard, 10% two, the rest none. Both are drawn from the single HAZARDS stream by index,
// so the second hazard cannot disturb any other axis.
private fun hazardsFrom(stream: Long): Set<Hazard> {
    val count = when (percentFrom(draw(stream, 0))) {
        in 0 until GalaxyBalance.ONE_HAZARD_PERCENT -> 1
        in GalaxyBalance.ONE_HAZARD_PERCENT until
            GalaxyBalance.ONE_HAZARD_PERCENT + GalaxyBalance.TWO_HAZARD_PERCENT -> 2
        else -> 0
    }
    if (count == 0) return emptySet()

    val first = Hazard.entries[draw(stream, 1).boundedBy(Hazard.entries.size)]
    if (count == 1) return setOf(first)
    // Picked from what is left, so a two-hazard world really has two.
    val remaining = Hazard.entries - first
    return setOf(first, remaining[draw(stream, 2).boundedBy(remaining.size)])
}

// A relay is a system-level feature, so it is drawn from the system's stream. Inert in 0.2: the
// screen may label it, it may not be tappable, and no holding mechanic exists to hold it with.
fun relayAt(seed: GalaxySeed, galaxy: Int, system: Int): GalaxyCoordinate? {
    val system0 = systemSeed(seed, galaxy, system)
    if (streamOf(system0, GenerationAxis.RELAY).boundedBy(GalaxyBalance.RELAY_SYSTEM_IN) != 0) return null

    val free = (1..GalaxyBalance.SLOTS_PER_SYSTEM)
        .map { slot -> GalaxyCoordinate(galaxy = galaxy, system = system, slot = slot) }
        .filter { at -> worldAt(seed, at) == null }
    // A system whose fifteen slots are all occupied has nowhere to put one. Astronomically rare
    // rather than impossible, so it is answered rather than asserted away.
    if (free.isEmpty()) return null
    return free[streamOf(system0, GenerationAxis.RELAY_SLOT).boundedBy(free.size)]
}

// Where the empire starts. Derived from the seed rather than stored as a constant, so a seed names
// a whole map including its own origin — and then *is* stored in the save, because genesis runs
// once and nothing may re-derive it later.
//
// The rule: the first world, walking systems forward from a seeded start, that the unaided species
// actually tolerates. A species evolved on a world inside its own tolerance bands is close enough
// to a tautology to not count as an invented number; what it is not is a *decided* one — see the
// open calls in `balance-log.md`.
internal fun homeFor(seed: GalaxySeed): GalaxyCoordinate {
    val stream = streamOf(mix(seed.value), GenerationAxis.HOME)
    val galaxy = stream.boundedBy(GalaxyBalance.GALAXIES) + 1
    val firstSystem = draw(stream, 1).boundedBy(GalaxyBalance.SYSTEMS_PER_GALAXY)
    val unaided = GalaxyBalance.tolerance(AdaptationLevels.NONE)

    var firstOccupied: GalaxyCoordinate? = null
    for (offset in 0 until GalaxyBalance.SYSTEMS_PER_GALAXY) {
        val system = (firstSystem + offset).mod(GalaxyBalance.SYSTEMS_PER_GALAXY) + 1
        for (slot in 1..GalaxyBalance.SLOTS_PER_SYSTEM) {
            val at = GalaxyCoordinate(galaxy = galaxy, system = system, slot = slot)
            val world = worldAt(seed, at) ?: continue
            if (firstOccupied == null) firstOccupied = at
            val habitable = HostilityAxis.entries.all { axis ->
                world.traits.axisValue(axis) in unaided.bandOf(axis)
            }
            if (habitable) return at
        }
    }
    // No world in the whole galaxy passes every band — possible only if the constants are retuned
    // far past anything the distribution targets allow. Falling back keeps genesis total rather
    // than throwing on a map the player could still play.
    return checkNotNull(firstOccupied) { "galaxy $galaxy generated no worlds at all under seed $seed" }
}
