package dev.fardavide.oltre.core

// Generation is pure, O(1) per world, and reads nothing but the seed and the coordinate.
//
// Two properties are load-bearing and both are asserted by tests rather than left to good
// intentions:
//
// 1. **Locality.** `worldAt` answers for one coordinate without generating its neighbours, so the
//    Compose `Canvas` renders any viewport lazily and slice 5 never holds a galaxy in memory.
// 2. **Sub-stream stability.** Every axis is drawn from its *own* named stream, hashed from the
//    world's seed and an axis tag. So the galaxy generated by seed S today is the same galaxy under
//    seed S after the next three slices add fields to `World`. Draw a new axis off a shared
//    sequential stream instead and every future addition silently rerolls everyone's map —
//    `GalaxySubStreamTest` exists to fail loudly the moment someone does.
//
// Nothing here changes with time. `advance()` is untouched and **no hook is left for it**: in 0.2
// the galaxy is fixed the instant the seed is minted, and a speculative per-tick entry point would
// be a promise the design has not made. Surveying and ownership change through the save's galaxy
// state, not through the clock.

// SplitMix64's finalizer. Written out rather than taken from `kotlin.random.Random` because the map
// is part of the save format: a stdlib generator whose internals changed would silently reroll
// every installed player's galaxy, where these two constants cannot.
private const val MIX_A: Long = -0x40a7b892e31b1a47 // 0xBF58476D1CE4E5B9
private const val MIX_B: Long = -0x6b2fb644ecceee15 // 0x94D049BB133111EB

private fun mix(value: Long): Long {
    var z = value
    z = (z xor (z ushr 30)) * MIX_A
    z = (z xor (z ushr 27)) * MIX_B
    return z xor (z ushr 31)
}

// Odd, widely spaced multipliers so two coordinates that differ by one in different components
// cannot collide before the mix.
// Written as unsigned hex and converted, which is why these are `val` rather than `const val`: the
// recognisable constants are worth more to a reader than their two's-complement spellings.
private val GALAXY_SALT: Long = 0x9E3779B97F4A7C15uL.toLong()
private val SYSTEM_SALT: Long = 0xC2B2AE3D27D4EB4FuL.toLong()
private val SLOT_SALT: Long = 0x165667B19E3779F9uL.toLong()

// Successive draws inside one axis — the second hazard after the first. Never used to reach a
// *different* axis, which is the whole point of the tags below.
private val DRAW_STEP: Long = 0x27D4EB2F165667C5uL.toLong()

// One named stream per generated quantity. **Adding a constant here is free; reordering or reusing
// one is a save-format change**, because every existing seed would produce a different galaxy.
// A new trait in a later slice takes a new tag and shifts nothing that already exists.
internal enum class GenerationAxis(val tag: Long) {
    OCCUPANCY(0x1D8E4E27C47D124FuL.toLong()),
    STAR_CLASS(0x2545F4914F6CDD1DuL.toLong()),
    TEMPERATURE_JITTER(0x3C79AC492BA7B653uL.toLong()),
    GRAVITY(0x4F1BBCDD8E4E27C4uL.toLong()),
    PRESSURE(0x5851F42D4C957F2DuL.toLong()),
    HAZARDS(0x6A09E667F3BCC909uL.toLong()),
    RELAY(0x7F4A7C15F39CC060uL.toLong()),
    RELAY_SLOT(0x8EBC6AF09C88C6E3uL.toLong()),
    HOME(0x9E3779B97F4A7C55uL.toLong()),

    // Which of the ten regions of a galaxy gets which temperament. Drawn from the *galaxy's* seed,
    // because a region is a property of a galaxy's layout rather than of any system in it.
    REGION(0xA54FF53A5F1D36F1uL.toLong()),

    // What a system and a region are called. Adding this tag is the sub-stream rule paying for
    // itself: 4,700 worlds get names and not one existing trait moves.
    NAMES(0xB5026F5AA96619E9uL.toLong()),

    // Whether a world wears a ring. The only generated quantity in the game that no rule reads.
    RING(0xC6EF372FE94F82BEuL.toLong()),

    // Where a system is *drawn* — its drift inside its band's lane and the wobble on its star's
    // radius. Appended like every tag before it, so a map somebody has been playing for a fortnight
    // is the same map the first time it is drawn: the drawing is new, the galaxy is not.
    LAYOUT(0xD1B54A32D192ED03uL.toLong()),
}

// The galaxy's own seed, shared by every system in it. Extracted from `systemSeed` rather than
// inlined there because the region layout is drawn at this level — one hash chain, stopped two
// steps early instead of one.
internal fun galaxySeed(seed: GalaxySeed, galaxy: Int): Long = mix(mix(seed.value) + GALAXY_SALT * galaxy)

// The system's own seed, shared by every slot in it — which is why the star class is the same for
// all of them. Deliberately the prefix of `worldSeed`: one hash chain, stopped a step earlier.
internal fun systemSeed(seed: GalaxySeed, galaxy: Int, system: Int): Long =
    mix(galaxySeed(seed, galaxy) + SYSTEM_SALT * system)

internal fun worldSeed(seed: GalaxySeed, at: GalaxyCoordinate): Long =
    mix(systemSeed(seed, at.galaxy, at.system) + SLOT_SALT * at.slot)

internal fun streamOf(baseSeed: Long, axis: GenerationAxis): Long = mix(baseSeed + axis.tag)

internal fun draw(stream: Long, index: Int): Long = mix(stream + DRAW_STEP * index)

// `mod` rather than `%` throughout: a hash is as often negative as positive, and `%` would make
// half the galaxy fall outside every range.
internal fun Long.boundedBy(bound: Int): Int = mod(bound.toLong()).toInt()

internal fun uniformFrom(stream: Long): Uniform = Uniform(stream.boundedBy(Uniform.BASIS + 1))

internal fun percentFrom(stream: Long): Int = stream.boundedBy(100)

// Which of a galaxy's ten regions a system falls in, 1-based. Fixed boundaries rather than
// generated ones: regions of varying width per seed buy nothing a player can perceive and cost this
// one line of arithmetic, plus the ability to compare one galaxy with another.
fun regionOf(system: Int): Int = (system - 1) / GalaxyBalance.SYSTEMS_PER_REGION + 1

// The galaxy's ten regions in order, as a **permutation** of `REGION_TEMPERAMENTS` — see the note
// there for why it is a shuffle of a fixed list and not ten draws.
//
// Fisher–Yates, one draw per position from the galaxy's own REGION stream, so the layout is a
// function of the seed and the galaxy and of nothing else. Ten elements, so building the whole list
// to answer for one region keeps `worldAt`'s locality promise intact.
fun temperamentsOf(seed: GalaxySeed, galaxy: Int): List<RegionTemperament> {
    val stream = streamOf(galaxySeed(seed, galaxy), GenerationAxis.REGION)
    val order = GalaxyBalance.REGION_TEMPERAMENTS.toMutableList()
    for (index in order.lastIndex downTo 1) {
        val other = draw(stream, index).boundedBy(index + 1)
        val held = order[index]
        order[index] = order[other]
        order[other] = held
    }
    return order
}

fun temperamentOf(seed: GalaxySeed, galaxy: Int, region: Int): RegionTemperament =
    temperamentsOf(seed, galaxy)[region - 1]

fun temperamentAt(seed: GalaxySeed, galaxy: Int, system: Int): RegionTemperament =
    temperamentOf(seed, galaxy, regionOf(system))

fun starClassAt(seed: GalaxySeed, galaxy: Int, system: Int): StarClass = GalaxyBalance.starClass(
    temperament = temperamentAt(seed, galaxy, system),
    percent = percentFrom(streamOf(systemSeed(seed, galaxy, system), GenerationAxis.STAR_CLASS)),
)

// ±half the band pitch. Claude Design's `looks-near-is-near` settled both halves of that: *"half the
// pitch, so it can never reorder two stars; enough that the band reads as sky"*. The cap is the
// safety argument in a number — path order is index order and the map's whole claim is that a
// distance on the drawing is a distance in the game, so a star that wandered into its neighbour's
// lane would make the drawing contradict the thing it draws.
private const val DRIFT_LIMIT: Int = 500

// The design's `0.82 + u * 0.36`, in thousandths of the star class's own radius. Wide enough that
// two standards in one band are siblings rather than clones, and stopped well short of the next
// class's radius so the wobble can never read as a promotion: size *is* class on this map, and a
// star drawn bigger than its class allows would be the map's one measurement telling a lie.
private const val SIZE_FLOOR: Int = 820
private const val SIZE_CEILING: Int = 1_180

// Where a system sits on the drawn map, how big its star is drawn, and which halo a bright one
// wears. Position *along* a band is arithmetic the map does for itself — twenty-five systems a band,
// `(n - 1) % 25` over 24 — so these three are all the drawing has to ask the seed for, and it has to
// ask: an even pitch on a straight line reads as a table, and every player on one seed has to be
// looking at the same sky.
//
// **Permille rather than dp, and integers rather than a Float or a Double.** `core` compiles for the
// JVM and for Kotlin/Native, and a galaxy that differs by a unit between two platforms is a
// different galaxy — the one promise this whole file exists to keep. Thousandths of a *pitch* and of
// a *class radius* also keep the numbers out of the drawing's business: the map decides what a pitch
// is at 393dp and again at 320dp, and this answers the same either way.
data class SystemLayout(val driftPermille: Int, val sizePermille: Int, val haloPermille: Int)

fun layoutAt(seed: GalaxySeed, galaxy: Int, system: Int): SystemLayout {
    // The *system's* stream, like the star class above it: a star is drawn once for the system it
    // is, and its fifteen slots have nothing to say about where that system sits. Both quantities
    // come off the one LAYOUT tag by index, which is what `draw` is for — a second tag would spend a
    // save-format constant on what is one thing, and a shared sequential stream would be the hazard
    // the note at the top of this file names.
    val stream = streamOf(systemSeed(seed, galaxy, system), GenerationAxis.LAYOUT)
    return SystemLayout(
        driftPermille = draw(stream, 0).boundedBy(2 * DRIFT_LIMIT + 1) - DRIFT_LIMIT,
        sizePermille = draw(stream, 1).boundedBy(SIZE_CEILING - SIZE_FLOOR + 1) + SIZE_FLOOR,
        // A third draw off the same tag, and it is *not* a displacement: it is which of the two halo
        // hues a bright star wears, thresholded by the drawing. Generated rather than picked by the
        // renderer for the reason the other two are — two players on one seed have to be looking at
        // the same sky, and "every third bright" chosen at draw time would depend on iteration order.
        haloPermille = draw(stream, 2).boundedBy(1_000),
    )
}

// The entry point. Null when the slot is empty, which is most of them.
fun worldAt(seed: GalaxySeed, at: GalaxyCoordinate): World? {
    val world = worldSeed(seed, at)
    if (percentFrom(streamOf(world, GenerationAxis.OCCUPANCY)) >= GalaxyBalance.occupancyPercent(at.slot)) {
        return null
    }

    val starClass = starClassAt(seed, at.galaxy, at.system)
    val jitterSpan = 2 * GalaxyBalance.TEMPERATURE_JITTER + 1
    val jitter = streamOf(world, GenerationAxis.TEMPERATURE_JITTER).boundedBy(jitterSpan) -
        GalaxyBalance.TEMPERATURE_JITTER
    val temperature = GalaxyBalance.temperature(at.slot, starClass, jitter)
    val gravity = GalaxyBalance.gravity(uniformFrom(streamOf(world, GenerationAxis.GRAVITY)))
    val pressure = GalaxyBalance.pressure(uniformFrom(streamOf(world, GenerationAxis.PRESSURE)))

    return World(
        at = at,
        starClass = starClass,
        // **Means nothing, on purpose.** One world in `RING_IN` is memorable for no reason at all,
        // and "the one with the ring" is a sentence a player says about a place rather than about a
        // statistic. It is on `World` rather than on `WorldTraits` because a survey is not what
        // reveals it — a ring is visible from home, like the star class, and the portrait only draws
        // one because the portrait is only drawn once a world is surveyed anyway.
        hasRing = streamOf(world, GenerationAxis.RING).boundedBy(GalaxyBalance.RING_IN) == 0,
        traits = WorldTraits(
            temperature = temperature,
            gravity = gravity,
            pressure = pressure,
            // Derived, never rolled — the pillar in three lines.
            metalRichness = GalaxyBalance.metalRichness(gravity),
            crystalRichness = GalaxyBalance.crystalRichness(pressure),
            deuteriumRichness = GalaxyBalance.deuteriumRichness(temperature),
            hazards = hazardsFrom(streamOf(world, GenerationAxis.HAZARDS)),
            fields = GalaxyBalance.fields(gravity),
        ),
    )
}

// 35% one hazard, 10% two, the rest none. Both are drawn from the single HAZARDS stream by index,
// so the second hazard cannot disturb any other axis.
private fun hazardsFrom(stream: Long): Set<Hazard> {
    val count = when (percentFrom(draw(stream, 0))) {
        in 0 until GalaxyBalance.ONE_HAZARD_PERCENT -> 1
        in GalaxyBalance.ONE_HAZARD_PERCENT until
            GalaxyBalance.ONE_HAZARD_PERCENT + GalaxyBalance.TWO_HAZARD_PERCENT -> 2
        else -> 0
    }
    if (count == 0) return emptySet()

    val first = Hazard.entries[draw(stream, 1).boundedBy(Hazard.entries.size)]
    if (count == 1) return setOf(first)
    // Picked from what is left, so a two-hazard world really has two.
    val remaining = Hazard.entries - first
    return setOf(first, remaining[draw(stream, 2).boundedBy(remaining.size)])
}

// A relay is a system-level feature, so it is drawn from the system's stream. Inert in 0.2: the
// screen may label it, it may not be tappable, and no holding mechanic exists to hold it with.
fun relayAt(seed: GalaxySeed, galaxy: Int, system: Int): GalaxyCoordinate? {
    val system0 = systemSeed(seed, galaxy, system)
    if (streamOf(system0, GenerationAxis.RELAY).boundedBy(GalaxyBalance.RELAY_SYSTEM_IN) != 0) return null

    val free = (1..GalaxyBalance.SLOTS_PER_SYSTEM)
        .map { slot -> GalaxyCoordinate(galaxy = galaxy, system = system, slot = slot) }
        .filter { at -> worldAt(seed, at) == null }
    // A system whose fifteen slots are all occupied has nowhere to put one. Astronomically rare
    // rather than impossible, so it is answered rather than asserted away.
    if (free.isEmpty()) return null
    return free[streamOf(system0, GenerationAxis.RELAY_SLOT).boundedBy(free.size)]
}

// Where the empire starts. Derived from the seed rather than stored as a constant, so a seed names
// a whole map including its own origin — and then *is* stored in the save, because genesis runs
// once and nothing may re-derive it later.
//
// The rule: the first world, walking systems forward from a seeded start, that the unaided species
// actually tolerates — **in a system that also holds somewhere to go.** A species evolved on a
// world inside its own tolerance bands is close enough to a tautology to not count as an invented
// number; what it is not is a *decided* one — see the open calls in `balance-log.md`.
//
// ── Why the second clause exists (0.5.1) ────────────────────────────────────────────────────
//
// The first clause was the whole rule until Davide played it: *"Galaxy interactions are too tough
// in the early game ... I need to upgrade at least 4 adaptations for the easier planet."*
//
// Genesis surveys the home system and nothing else, so its non-home worlds are the entire content
// of the Galaxy screen on day one — and they were drawn from the same distribution as the rest of
// the map, where 98.2% of worlds are blocked and the median blocked world fails two axes. What
// that costs a player rather than a map is what `:sim:run`'s doorstep report measures: over 1,000
// seeds the **median home system asked for seven adaptation levels** across two ladders, at 54,242
// resources priced 1 : 2 : 3 and 39 hours of the one shared research slot, before anything on that
// screen would say something different. 78% were asked for four or more. Davide's own colony, at
// five, was in the better third.
//
// So the map was never the thing that was too hard — **the sample was**. Adaptation doubles the
// settleable count of the galaxy with every level, exactly as `galaxy-sheet.md` §9 designed, and a
// player looking at 4.75 worlds cannot see a galaxy-wide statistic. Widening the bands to fix it
// would raise `passes every band` with them, which §9 names as the one thing not to do; making a
// level widen further would make adaptation stronger everywhere to fix a sampling problem in one
// system. **Choosing which system you start in changes no world's traits at all** — every
// distribution in `GalaxyDistributionTest` is untouched by construction, because the galaxy is the
// same galaxy and only the origin moved.
//
// The walk therefore keeps the best system it has seen and stops at the first that is good enough.
// It does not fall back to "any tolerable world" until the whole space has been read, so a seed
// that genuinely has nothing within `DOORSTEP_LEVELS` still gets the nearest thing there is rather
// than the first thing walked past.
//
// **One level, and the walk crosses galaxies to find it.** Both halves were measured rather than
// chosen. A system that holds a tolerable world *and* a neighbour one level away is 0.50% of all
// systems, so a walk bounded to the seeded galaxy's 250 finds one 77% of the time — measured, and
// close to the 71% the arithmetic predicts. Over the whole 1,000-system space it is 99.8%. The
// seeded galaxy is the *start* of the walk rather than its bound, and is walked whole before any
// other is looked at — see the loop — so a colony still opens in the galaxy its seed names unless
// that galaxy has nothing to offer. The cost is a genesis that reads at most 15,000 slots once.
// Two levels inside one galaxy was the other way to reach the same reliability and it buys a worse
// promise: two levels is two projects through the one shared research slot, and may be two
// different ladders, so it is no longer true that *your first adaptation level opens a world you
// can see*.
private const val DOORSTEP_LEVELS: Int = 1

private fun homeStream(seed: GalaxySeed): Long = streamOf(mix(seed.value), GenerationAxis.HOME)

// The galaxy a seed names. Extracted rather than inlined below because the walk's promise — *you
// open where your seed says unless that galaxy has nothing* — was stated only in a comment, and a
// draft that broke it for half of all colonies passed every test in the suite. A promise about a
// draw needs the draw to be nameable from a test.
internal fun seededGalaxyOf(seed: GalaxySeed): Int =
    homeStream(seed).boundedBy(GalaxyBalance.GALAXIES) + 1

internal fun homeFor(seed: GalaxySeed): GalaxyCoordinate {
    val stream = homeStream(seed)
    val firstGalaxy = seededGalaxyOf(seed) - 1
    val firstSystem = draw(stream, 1).boundedBy(GalaxyBalance.SYSTEMS_PER_GALAXY)

    var firstOccupied: GalaxyCoordinate? = null
    var best: GalaxyCoordinate? = null
    var bestDoorstep = Int.MAX_VALUE

    // **Nested rather than one flat index over the 1,000 systems, and the difference is not
    // cosmetic.** A flat walk leaves the seeded galaxy the moment its *tail* runs out — a colony
    // starting at system 200 sees fifty systems of its own galaxy and then a whole other one — which
    // measured at **50%** of colonies opening outside the galaxy their seed names. Walking the
    // seeded galaxy whole first, wrapping inside it, takes that to **22%** at the same success rate
    // and the same scan cost. The seeded galaxy is meant to be where you start; a walk that
    // abandons it half the time makes the draw at the top of this function decorative.
    outer@ for (step in 0 until GalaxyBalance.GALAXIES) {
        val galaxy = (firstGalaxy + step).mod(GalaxyBalance.GALAXIES) + 1
        for (offset in 0 until GalaxyBalance.SYSTEMS_PER_GALAXY) {
            val system = (firstSystem + offset).mod(GalaxyBalance.SYSTEMS_PER_GALAXY) + 1
            val worlds = (1..GalaxyBalance.SLOTS_PER_SYSTEM).mapNotNull { slot ->
                worldAt(seed, GalaxyCoordinate(galaxy = galaxy, system = system, slot = slot))
            }
            if (worlds.isEmpty()) continue
            if (firstOccupied == null) firstOccupied = worlds.first().at

            // Still the first tolerable world of the system, in slot order — the clause that has
            // not changed, and the one the fiction rests on.
            val candidate = worlds.firstOrNull { GalaxyBalance.levelsToTolerate(it.traits) == 0 } ?: continue
            // How far the nearest *other* world is. `MAX_VALUE` when the system holds only the home
            // world, which is a real case and the worst one there is: a Galaxy screen whose opening
            // system has a single row on it.
            val doorstep = worlds
                .filter { it.at != candidate.at }
                .minOfOrNull { GalaxyBalance.levelsToTolerate(it.traits) }
                ?: Int.MAX_VALUE

            if (doorstep < bestDoorstep) {
                best = candidate.at
                bestDoorstep = doorstep
                if (doorstep <= DOORSTEP_LEVELS) break@outer
            }
        }
    }
    // No world anywhere passes every band — possible only if the constants are retuned far past
    // anything the distribution targets allow. Falling back keeps genesis total rather than
    // throwing on a map the player could still play.
    return best ?: checkNotNull(firstOccupied) { "no galaxy generated any world at all under seed $seed" }
}
