package dev.fardavide.oltre.core

import kotlin.time.Duration
import kotlin.time.Duration.Companion.hours
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Instant

// **The whole balance surface, rendered as one deterministic page.**
//
// `OpeningBalanceTest` and `CheckInBalanceTest` are *bands* — they fail when the opening leaves the
// shape it is meant to have, and they deliberately say nothing while it moves inside that shape.
// That is the right instrument for a guardrail and the wrong one for a review, because the readings
// a band lets through are exactly the ones a designer wants to see before agreeing to them.
//
// So this is the other instrument: not an assertion about the balance but a **photograph** of it.
// `BalanceBenchmarkTest` compares this page against `BalanceBenchmarkGolden`, a plain string in the
// file next door, and the golden is committed. The consequence is the point —
//
//   **a change to any balance number shows up as a diff on a page of player-visible readings, in
//   the pull request, whether or not any band was crossed.**
//
// 0.5.1 is the case it is built for. That change moved the gate from Robotics 4 to Robotics 2 and
// re-homed every new colony, every test in the repository passed, and the review had nothing in
// front of it but prose. With this page, the same change arrives as thirty moved lines — the gate
// clock going 33h to 12h, the doorstep going 5 levels to 1, the research refusals trading places
// with the price refusals — and a reviewer can agree or disagree with the *effect* rather than with
// an argument about a constant.
//
// ── Reading it ───────────────────────────────────────────────────────────────────────────────
//
// Everything here is derived, never a constant copied out. A row that just restated
// `AdaptationBalance.GATE` would move when the constant moved and tell a reviewer nothing they did
// not already see in the diff; a row that says *what hour the branch opens* moves when the gate
// moves **and** when the build curve, the discount, the Robotics divisor or the opening stock move,
// which is the whole reason the page exists.
//
// The simulated colony is one player, played one way — every hour, buy the cheapest thing you can
// afford. It is not a good player and is not meant to be. It is a *fixed* player, so that a
// difference between two runs of this page is a difference in the game rather than in the strategy.
internal object BalanceBenchmark {

    // `trimEnd` because the golden next door is a `trimIndent`ed raw string, and `trimIndent`
    // drops the blank line before the closing quotes. Without this the two would differ by one
    // invisible character and the page would never match on any target.
    fun render(): String = buildString {
        appendLine("# Oltre balance benchmark")
        appendLine("#")
        appendLine("# Generated by BalanceBenchmarkTest from the balance objects in :core.")
        appendLine("# Every reading is derived. Do not hand-edit — regenerate and read the diff.")
        appendLine("#")
        appendLine("# The colony below checks in every hour and buys the cheapest thing it can")
        appendLine("# afford, buildings first, then whichever research project is cheapest. One")
        appendLine("# fixed player, so a diff on this page is a change to the game.")
        section(opening())
        section(session())
        section(progression())
        section(experience())
        section(pressure())
        section(economy())
        section(research())
        section(adaptation())
        section(galaxy())
        section(fleet())
        section(horizon())
        section(lateGame())
    }.trimEnd()

    // ── [opening] the landmarks, as a clock ──────────────────────────────────────────────────
    //
    // Every gate in the game is a Robotics Factory level, so the branch that opens on a level is
    // only as far away as the level is. These rows are what Davide's *"I needed 2 day to get
    // robotics to level 4"* reads as when the game says it rather than a player.
    private fun opening(): List<String> = buildList {
        val run = colony(days = LONG_HORIZON_DAYS)
        add("[opening] the hour each landmark lands, for a colony that checks in hourly")
        for (level in listOf(1, 2, 4, 9, 10)) {
            add(row("robotics factory $level", hourText(run.firstHourWhere { it.buildings.roboticsFactory.value >= level })))
        }
        add(row("mines past the opening discount (level 9)", hourText(run.firstHourWhere { it.buildings.metalMine.value >= 9 })))
        add(row("first applied technology finished", hourText(run.firstHourWhere { state -> Technology.entries.any { state.research.levelOf(it).value >= 1 } })))
        add(row("first adaptation level finished", hourText(run.firstHourWhere { state -> AdaptationTechnology.entries.any { state.research.levelOf(it).value >= 1 } })))
        // **"second skiff" until 0.11.3, and the rename is the whole of what this page saw of that
        // change.** Genesis stopped granting a hull, so the row the fixed player reaches here is the
        // *first* one — and the hour did not move, because this player buys buildings and never a
        // hull, so what it reads is when the stores first cover the price rather than when a fleet
        // appears. Worth knowing that this page is blind to the change: the reading that moved is in
        // `OpeningBalanceTest` and in the sim's fleet report, both of which have a player who buys
        // hulls. A benchmark is only as wide as its policy.
        add(row("first skiff affordable", hourText(run.firstHourWhere { it.resources.covers(FleetBalance.shipCost(ShipType.SKIFF)) })))
        // What `LATE_GAME_FIRST_LEVEL` is measured against: the ramp is supposed to begin where the
        // Nanite Factory becomes buildable, so if this row and that constant ever disagree, the
        // constant is wrong and this page is where it shows.
        val naniteOpens = run.firstHourWhere { it.buildings.roboticsFactory.value >= PlaceholderBalance.NANITE_ROBOTICS_REQUIREMENT }
        add(
            row(
                "metal mine when the nanite unlocks",
                "level ${naniteOpens?.let { run.at(it)?.buildings?.metalMine?.value } ?: 0}" +
                    " (ramp starts at ${PlaceholderBalance.LATE_GAME_FIRST_LEVEL})",
            ),
        )
    }

    // ── [session] what five minutes of the game holds ────────────────────────────────────────
    //
    // Round 16's readings, which is the round Davide asked for *"some adrenaline"* in. A build curve
    // that gets slower shows up here before it shows up anywhere else.
    private fun session(): List<String> = buildList {
        val landings = firstSitting()
        add("[session] completions a player is present for, minute by minute")
        add(row("first completion", if (landings.isEmpty()) "never" else "minute ${landings.min()}"))
        for (window in listOf(10, 30, 60)) {
            add(row("completions within $window min", "${landings.count { it <= window }}"))
        }
        add(row("longest silence in the first 15 min", "${longestGap(landings.filter { it <= 15 }, upTo = 15)}m"))
        add(row("longest silence in the first hour", "${longestGap(landings, upTo = 60)}m"))

        val visits = checkIns(days = 2)
        add(row("dead check-ins in the first two days", "${visits.count { it.finished == 0 && it.affordable == 0 }} of ${visits.size}"))
        add(row("check-ins offering two kinds of decision", "${visits.count { it.kinds >= 2 }} of ${visits.size}"))
        add(row("check-ins leaving work booked", "${visits.count { it.running > 0 }} of ${visits.size}"))
    }

    // ── [progression] is the colony still moving ─────────────────────────────────────────────
    private fun progression(): List<String> = buildList {
        val run = colony(days = LONG_HORIZON_DAYS)
        add("[progression] where the colony stands, day by day")
        // **Banked is split three ways rather than priced into one figure**, because the lopsided
        // bank is the failure this row exists to show and pricing hides it perfectly: round 7 found
        // a colony closing a week on 49,544 metal it had nothing to spend on against 1,410 crystal,
        // and a single priced total would have called that a healthy 52,364.
        add(row("day", "levels   income/h        metal    crystal      deut"))
        for (day in listOf(1, 2, 3, 7, 14)) {
            val state = run.at(day * 24) ?: continue
            val levels = BuildingType.entries.sumOf { state.buildings.levelOf(it).value }
            add(
                row(
                    "  day $day",
                    levels.toString().padStart(5) +
                        priced(income(state)).toString().padStart(11) +
                        state.resources.metal.toString().padStart(13) +
                        state.resources.crystal.toString().padStart(11) +
                        state.resources.deuterium.toString().padStart(10),
                ),
            )
        }
        // Which rows the levels are actually in. A total can hide a colony that has poured
        // everything into one facility because the others were busy.
        val end = checkNotNull(run.at(LONG_HORIZON_DAYS * 24))
        add("the tree at day $LONG_HORIZON_DAYS")
        for (building in OPENING_PLAN) {
            add(row("  ${label(building)}", "${end.buildings.levelOf(building).value}"))
        }
    }

    // ── [experience] how fast the badge above the rail moves ─────────────────────────────────
    //
    // **A floor rather than the figure, and the difference is worth reading before the rows are.**
    // This colony never buys a hull and never sends a probe, so it earns from two of the five things
    // that pay — which is deliberate here (the page photographs one fixed player and always has) and
    // is why these levels sit below the marks the curve was fitted to. The full player, with probes
    // and a fleet, is measured by `:sim:run`'s experience report and lands at Lv 3 / 11 / 16 / 25.
    //
    // What this catches is the half the sim cannot: the ladder and the awards are `core` constants,
    // so a round that moves a *cost* curve moves these rows too — deeper facilities finish later,
    // which is a level the player does not have on the day they used to have it.
    private fun experience(): List<String> = buildList {
        val run = colony(days = LONG_HORIZON_DAYS)
        add("[experience] the level a colony that only builds is wearing")
        add(row("day", "level    points   into the level"))
        for (day in listOf(1, 2, 3, 7, 14)) {
            val state = run.at(day * 24) ?: continue
            // The carried total, which is what the strip draws. `ExperienceTest` is what says it
            // still equals the fold; this page photographs the number the player sees.
            val progress = state.playerProgress()
            add(
                row(
                    "  day $day",
                    "Lv ${progress.level.value}".padStart(5) +
                        progress.earned.points.toString().padStart(10) +
                        "${progress.percent}%".padStart(10),
                ),
            )
        }
        // Where the points came from, which is the reading that says whether one verb has quietly
        // become the way to level. Two verbs here because this colony only has two.
        val closing = checkNotNull(run.at(LONG_HORIZON_DAYS * 24)).eventLog
        val fromBuilds = closing.filterIsInstance<Event.BuildCompleted>()
            .sumOf { ExperienceBalance.awardFor(it).points }
        val fromProjects = closing.filter { it is Event.ResearchCompleted || it is Event.AdaptationCompleted }
            .sumOf { ExperienceBalance.awardFor(it).points }
        add("where the points came from by day $LONG_HORIZON_DAYS")
        add(row("  facility levels", "$fromBuilds (${percent(fromBuilds, fromBuilds + fromProjects)})"))
        add(row("  projects and ladders", "$fromProjects (${percent(fromProjects, fromBuilds + fromProjects)})"))
        // The ladder itself, which is a property of the curve rather than of this colony — so it
        // moves when `ExperienceBalance` moves and at no other time.
        add("what the next level costs")
        for (level in listOf(0, 5, 10, 25)) {
            add(row("  leaving Lv $level", "${ExperienceBalance.spanOf(PlayerLevel(level)).points}"))
        }
    }

    // ── [pressure] which resource is the one saying no ───────────────────────────────────────
    //
    // Round 7's whole subject, and the reading that caught the 3:1 metal-to-crystal ratio being
    // wrong in 0.1.0 — a colony closing a week on 49,544 metal it had nothing to spend on. A
    // production-ratio change that leaves every curve's shape intact lands here and nowhere else.
    private fun pressure(): List<String> = buildList {
        val run = colony(days = LONG_HORIZON_DAYS)
        var blocked = 0
        val short = mutableMapOf<String, Int>()
        // **Read on arrival, before the colony spends.** Measured after spending, this section says
        // 99.4% and means nothing at all: a greedy player empties the bank every hour by
        // construction, so "can it afford the next row" is answered by the policy rather than by the
        // economy. What a player actually meets is the state the *check-in opens on*, which is the
        // state `advance` hands back before anything is bought.
        for (state in run.arrivals) {
            val cheapest = OPENING_PLAN
                .map { PlaceholderBalance.upgradeCost(it, next(state, it)) }
                .minByOrNull { priced(it) } ?: continue
            if (state.resources.covers(cheapest)) continue
            blocked++
            if (state.resources.metal < cheapest.metal) short["metal"] = (short["metal"] ?: 0) + 1
            if (state.resources.crystal < cheapest.crystal) short["crystal"] = (short["crystal"] ?: 0) + 1
            if (state.resources.deuterium < cheapest.deuterium) short["deuterium"] = (short["deuterium"] ?: 0) + 1
        }
        // Idleness is the opposite: it is a property of what the colony was *left* holding, so it is
        // read after the spend. Round 16 called this the biggest open item in the balance log.
        val idle = run.states.count {
            it.builds.isEmpty() && it.activeResearch == null && it.activeAdaptation == null
        }
        add("[pressure] over $LONG_HORIZON_DAYS days, which resource blocks the cheapest unbuilt row")
        add(row("hours opening with the cheapest row unaffordable", percent(blocked, run.arrivals.size)))
        for (kind in listOf("metal", "crystal", "deuterium")) {
            add(row("  of which short of $kind", percent(short[kind] ?: 0, maxOf(blocked, 1))))
        }
        add(row("hours with nothing building and no research", percent(idle, run.states.size)))
        // **The pile, explained in one number.** Earned is what arrived between two check-ins;
        // spent is what the colony managed to place before the next one. A colony that cannot place
        // what it earns is not a colony with a rich economy — it is a colony with nowhere to put it,
        // and the gap between these two is the pile in `[progression]`.
    //
    // **Split per resource, because that is what separates the two diagnoses.** A colony that
    // cannot place what it earns has either an economy running too fast — every resource piling up
    // together — or one resource the game does not ask for in the proportion it makes it. Those need
    // opposite fixes, and a single priced figure cannot tell them apart.
        val earned = mutableMapOf<ResourceKind, Long>()
        val spent = mutableMapOf<ResourceKind, Long>()
        fun of(resources: Resources, kind: ResourceKind): Long = when (kind) {
            ResourceKind.METAL -> resources.metal
            ResourceKind.CRYSTAL -> resources.crystal
            ResourceKind.DEUTERIUM -> resources.deuterium
        }
        for (hour in run.arrivals.indices) {
            for (kind in ResourceKind.entries) {
                val opened = of(run.arrivals[hour].resources, kind)
                spent[kind] = (spent[kind] ?: 0) + opened - of(run.states[hour].resources, kind)
                if (hour > 0) earned[kind] = (earned[kind] ?: 0) + opened - of(run.states[hour - 1].resources, kind)
            }
        }
        add(row("over the fortnight, per resource", "earned       spent     placed"))
        for (kind in ResourceKind.entries) {
            val made = earned[kind] ?: 0
            val used = spent[kind] ?: 0
            add(
                row(
                    "  ${kind.name.lowercase()}",
                    made.toString().padStart(9) + used.toString().padStart(12) +
                        percent((used * 100 / maxOf(made, 1)).toInt(), 100).padStart(11),
                ),
            )
        }
    }

    // ── [economy] what a level costs and what it gives back ──────────────────────────────────
    //
    // Payback is the reading round 11 was argued from — cost compounds at +50% and output at +25%,
    // so payback grows with depth *by design*, and the question a benchmark has to answer is how
    // fast. A curve change that keeps both shapes and moves their relationship shows up in this
    // column and in no assertion anywhere.
    private fun economy(): List<String> = buildList {
        add("[economy] cost, wait and payback per level, at robotics factory 4")
        add(row("building / level", "priced    build     +income/h   payback"))
        for (building in OPENING_PLAN) {
            for (level in listOf(1, 5, 10, 20)) {
                val cost = PlaceholderBalance.upgradeCost(building, BuildingLevel(level))
                val wait = PlaceholderBalance.upgradeDuration(building, BuildingLevel(level), BuildingLevel(4), BuildingLevel(0))
                val gain = incomeGain(building, level)
                add(
                    row(
                        "  ${label(building)} $level",
                        priced(cost).toString().padStart(9) +
                            clock(wait).padStart(9) +
                            (if (gain == 0L) "-" else gain.toString()).padStart(12) +
                            (if (gain == 0L) "-" else ratio(priced(cost), gain) + "h").padStart(10),
                    ),
                )
            }
        }
        val day2 = checkNotNull(colony(days = 2).at(48))
        val energy = PlaceholderBalance.energyBalance(day2.buildings, day2.research)
        add(row("day-2 colony energy", "${energy.produced} produced / ${energy.consumed} consumed"))
        add(row("day-2 colony energy headroom", "${PlaceholderBalance.energyHeadroomLevels(day2.buildings, day2.research)} levels"))
    }

    // ── [research] the applied branch, and whether a level is ever worth the slot ────────────
    private fun research(): List<String> = buildList {
        val day3 = checkNotNull(colony(days = 3).at(72))
        add("[research] cost, wait and effect per level, at robotics factory 4")
        add(row("technology / level", "priced    wait      effect   payback"))
        for (technology in Technology.entries) {
            for (level in 1..5) {
                val cost = ResearchBalance.researchCost(technology, TechLevel(level))
                val wait = ResearchBalance.researchDuration(technology, TechLevel(level), BuildingLevel(4))
                val effect = ResearchBalance.effectPercent(technology, TechLevel(level))
                val gain = researchGain(day3, technology, level)
                add(
                    row(
                        "  ${label(technology)} $level",
                        priced(cost).toString().padStart(9) +
                            clock(wait).padStart(10) +
                            "+$effect%".padStart(9) +
                            (if (gain <= 0L) "-" else ratio(priced(cost), gain) + "h").padStart(10),
                    ),
                )
            }
        }
    }

    // ── [adaptation] the second branch, priced against the first ────────────────────────────
    //
    // The two branches share one empire-wide slot, so what matters is not either table but the
    // **ratio** between them: the adaptation sheet's argument for 4,800 is that a ladder level costs
    // about twice the priciest applied technology. A discount that reached one branch and not the
    // other broke that once already, at 5.8x, and this row is where that would have been visible.
    private fun adaptation(): List<String> = buildList {
        add("[adaptation] cost and wait per level, at the gate's own robotics level")
        val gate = AdaptationBalance.GATE
        add(row("ladder / level", "priced    wait      x priciest applied"))
        for (ladder in AdaptationTechnology.entries) {
            for (level in 1..5) {
                val cost = AdaptationBalance.adaptationCost(ladder, TechLevel(level))
                val wait = AdaptationBalance.adaptationDuration(ladder, TechLevel(level), gate)
                val dearest = Technology.entries.maxOf { priced(ResearchBalance.researchCost(it, TechLevel(level))) }
                add(
                    row(
                        "  ${label(ladder)} $level",
                        priced(cost).toString().padStart(9) +
                            clock(wait).padStart(10) +
                            ratio(priced(cost), dearest).padStart(20),
                    ),
                )
            }
        }
    }

    // ── [galaxy] the map, and what a ladder level buys on it ────────────────────────────────
    //
    // The galaxy-wide rows are what `GalaxyDistributionTest` asserts; they are reproduced here
    // because the doorstep rows underneath them are meaningless without the distribution they sit
    // in. **The doorstep rows are the ones 0.5.1 shipped without** — a whole-galaxy statistic said
    // an adaptation level roughly doubles the settleable count, and a player standing in one system
    // met a wall, because a colony's sample is its own home system and nothing else.
    private fun galaxy(): List<String> = buildList {
        val worlds = wholeGalaxy()
        val unaided = GalaxyBalance.tolerance(AdaptationLevels.NONE)
        add("[galaxy] the map as generated, from seed ${TEST_GALAXY_SEED.value}")
        add(row("worlds in the coordinate space", "${worlds.size} of ${GalaxyBalance.TOTAL_SLOTS} slots"))
        for (axis in HostilityAxis.entries) {
            add(row("  ${label(axis)} band passes", percent(worlds.count { it.traits.axisValue(axis) in unaided.bandOf(axis) }, worlds.size)))
        }
        add(row("  passes every band", percent(worlds.count { world -> HostilityAxis.entries.all { world.traits.axisValue(it) in unaided.bandOf(it) } }, worlds.size)))
        add(row("settleable at adaptation level", "count    share"))
        for (level in listOf(0, 1, 2, 3, 4, 6)) {
            val tolerance = GalaxyBalance.tolerance(AdaptationLevels(level, level, level))
            val settleable = worlds.count { world ->
                HostilityAxis.entries.all { world.traits.axisValue(it) in tolerance.bandOf(it) } &&
                    GalaxyBalance.yieldScore(world.traits).perMillion >= GalaxyBalance.WORTH_IT_THRESHOLD.perMillion
            }
            add(row("  all three ladders at $level", settleable.toString().padStart(5) + percent(settleable, worlds.size).padStart(9)))
        }

        val openings = (0 until BENCHMARK_SEEDS).map { offset ->
            val seed = GalaxySeed(TEST_GALAXY_SEED.value + offset)
            val state = GalaxyState.initial(seed)
            state.surveyed.filter { it != state.home }
                .mapNotNull { worldAt(seed, it) }
                .map { GalaxyBalance.levelsToTolerate(it.traits) }
                .sorted()
        }
        add("[galaxy] the opening screen, over $BENCHMARK_SEEDS colonies")
        add(row("non-home worlds on the screen, median", "${openings.map { it.size }.median()}"))
        for ((index, name) in listOf("cheapest", "second", "third").withIndex()) {
            add(row("  $name neighbour, levels away, median", "${openings.mapNotNull { it.getOrNull(index) }.median()}"))
        }
        add(row("colonies with a neighbour at one level", percent(openings.count { (it.firstOrNull() ?: 99) <= 1 }, openings.size)))
        add(row("colonies with every neighbour blocked", percent(openings.count { it.isNotEmpty() && it.all { levels -> levels > 0 } }, openings.size)))
    }

    // ── [fleet] the hull price, and when the second one lands ───────────────────────────────
    private fun fleet(): List<String> = buildList {
        // **One row where there were five, which is 0.10.1 in one line.** This block printed a curve
        // — five rungs of a x1.5 price and five of the wait taken from it — and Davide's call made
        // the price flat, so five rows would be the same row five times. What the page has to carry
        // instead is the thing that *does* grow with a fleet, and that is the queue: see the yard row.
        add("[fleet] the hull price and one representative run")
        val cost = FleetBalance.shipCost(ShipType.SKIFF)
        add(row("  every skiff", "${cost.metal} metal / ${cost.crystal} crystal, priced ${priced(cost)}"))
        // **The yard, at both ends of the one building that answers it.** Two columns rather than
        // one, because 0.9.0's wait is the first number in the game a player can shorten by building
        // something they were going to build anyway — and a page showing only the Robotics 0 column
        // would report the wait of a colony nobody has after day two. Since the price went flat this
        // is also the *only* thing that makes the fifth hull cost more than the first, so the row
        // states what five in one order come to.
        val alone = FleetBalance.buildDuration(ShipType.SKIFF, BuildingLevel(0))
        val helped = FleetBalance.buildDuration(ShipType.SKIFF, BuildingLevel(4))
        add(row("  every skiff takes", "${clock(alone)} at robotics 0 · ${clock(helped)} at robotics 4"))
        add(row("  five in one order take", "${clock(alone * 5)} at robotics 0 · ${clock(helped * 5)} at robotics 4"))
        val home = GalaxyState.initial(TEST_GALAXY_SEED).home
        val neighbour = home.copy(slot = if (home.slot == 1) 2 else 1)
        val window = 6.hours
        val unresearched = Research.initial()
        add(row("6h run to the next slot, round trip", clock(FleetBalance.roundTrip(home, neighbour, unresearched, FleetBalance.FASTEST_HULL))))
        add(
            row(
                "  station time",
                clock(FleetBalance.stationFor(home, neighbour, window, unresearched, FleetBalance.FASTEST_HULL)),
            ),
        )
        val average = World(
            at = neighbour,
            starClass = StarClass.STANDARD,
            traits = worldAt(TEST_GALAXY_SEED, home)?.traits ?: error("home has no world"),
            hasRing = false,
        )
        val cargo = FleetBalance.cargo(
            world = average,
            gathering = ResourceKind.METAL,
            ships = Ships.of(ShipType.SKIFF, 1),
            station = FleetBalance.stationFor(home, neighbour, window, unresearched, FleetBalance.FASTEST_HULL),
            danger = 0,
            research = unresearched,
        )
        add(row("  one skiff brings home", "${cargo.metal} metal"))
        add(row("  as hours of a genesis colony's metal", ratio(cargo.metal, PlaceholderBalance.metalProductionPerHour(BuildingLevel(1))) + "h"))

        // **The reading Davide's 2026-08-13 complaint was about, and the one the page could not
        // make before.** *"Ships are WAY too cheap, considered the benefits they bring back"* is a
        // statement about a ratio, and nothing here printed one: the curve was on the page and the
        // hold was on the page and what it costs to *earn* a hull was left to the reader.
        //
        // Station-hours rather than wall-clock hours, deliberately — flight is a property of the
        // target and station is what the hull is paid for. At 1.00 the hull has repaid its own price
        // once. Held at richness 1.0 and danger 0, so it is the floor of what a hull is worth rather
        // than the best case.
        val perStationHour = FleetBalance.EXTRACTION_PER_HOUR
        add(
            row(
                "  a skiff repays itself in",
                "${priced(FleetBalance.shipCost(ShipType.SKIFF)) / perStationHour} station-hours",
            ),
        )

        // **Is the frontier worth crossing the map for** — round 21's whole question, in four rows.
        // One richness throughout (the home world's), the 24h rung throughout, so the only things
        // moving are the flight the window loses and the danger it gains. Before round 21 every row
        // below 1.00 was a world nobody would ever send a ship to, and the sim measured exactly that:
        // 56 of 56 dispatches to band 0. **A row under 1.00 is distance still winning.**
        add("[frontier] the 24h rung at one richness — what distance and danger are worth")
        val nearHold = frontierHold(home, neighbour, average)
        for ((name, target) in frontierTargets(home)) {
            val hold = frontierHold(home, target, average)
            val band = FleetBalance.distanceBand(home, target)
            val trip = clock(FleetBalance.roundTrip(home, target, unresearched, FleetBalance.FASTEST_HULL))
            add(row("  $name", "band $band · round trip $trip · ${hold} metal · ${ratio(hold, nearHold)}x"))
        }

        // **The drive, and the reading that says whether it is worth a research slot.** Distance is
        // the only thing this technology touches, so the page has to show it where distance lives:
        // the same four targets, at four levels, in round trip and in the rungs the ladder will
        // offer. A row whose ladder is empty is a target the player cannot reach at all.
        //
        // `exploration-rewards-sheet.md` §6.3 asks for exactly this table, *"reproduced from the
        // shipped formulas rather than from this document's arithmetic"* — so it is computed here
        // and never copied.
        add("[drive] what a Propulsion level buys, per target — round trip · rungs the ladder offers")
        for ((name, target) in frontierTargets(home)) {
            for (level in listOf(0, 1, 3, 5)) {
                val research = unresearched.withLevel(Technology.PROPULSION, TechLevel(level))
                val rungs = FleetBalance.windowsFor(home, target, research, FleetBalance.FASTEST_HULL)
                val ladder = if (rungs.isEmpty()) "out of reach" else rungs.joinToString(" · ") { clock(it) }
                add(row("  $name at drive $level", "${clock(FleetBalance.roundTrip(home, target, research, FleetBalance.FASTEST_HULL))} · $ladder"))
            }
        }

        // **Design's one number to check before this ships** — *Twice the Flight*, closing line:
        // *"The hauler is worth 630 metal at exactly one rung on a doorstep world and nothing at four
        // of the five. If `:sim:run` agrees, the hull is a purchase that pays only on deep veins far
        // out."* This is that reading, from the shipped formulas rather than from the design's
        // arithmetic, and it is on the page permanently rather than checked once.
        //
        // **Two rows, because there are two questions and only one of them is the design's.**
        //
        // *Per berth* a hauler is strictly worse and always will be: `cargo` is berths x rate x
        // station, four skiffs and one hauler carry the same four berths, and the hauler spends more
        // of the window flying. That is `fleet-sheet.md` §8's own long-standing claim — *"strictly
        // worse per berth at every target and window"* — and it is why the hull's entire case is
        // price. Printed so nobody re-derives it as a defect.
        //
        // *Per pool* is the question the sheet actually asks, and it is the one Design's cells put
        // in front of the player: **what your idle hulls carry with the hauler against without it.**
        // Their fixture is one hauler and two skiffs, so the two cells are 2 berths and 6 berths —
        // three times the hold for double the flight — and the rung where that stops paying is the
        // crossover the hull is bought for.
        add("[hauler] per berth — four skiffs against one hauler, which the hauler always loses")
        for (rung in FleetBalance.WINDOWS) {
            add(row("  per berth, the next slot at ${clock(rung)}", pairing(neighbour, rung, unresearched, average, EQUAL_BERTHS)))
        }
        add("[hauler] per pool — Design's own cells: two skiffs against a hauler and two skiffs")
        val adjacentGalaxy = frontierTargets(home).last().second
        for ((name, target) in listOf("the next slot" to neighbour, "the next galaxy" to adjacentGalaxy)) {
            for (rung in FleetBalance.WINDOWS) {
                add(row("  per pool, $name at ${clock(rung)}", pairing(target, rung, unresearched, average, DESIGNS_POOL)))
            }
        }

        // **The row that decides whether the drive competes rather than dominates** — §6.5's merge
        // condition, stated as a hold. It is the same 24h rung at the same richness as `[frontier]`,
        // so the two sections read against each other: what a level of reach is worth at a target,
        // against what a level of Prospecting is worth everywhere.
        add("[drive] one skiff on the 24h rung at the adjacent galaxy, by level")
        val hop = frontierTargets(home).last().second
        for (level in 0..3) {
            val drive = unresearched.withLevel(Technology.PROPULSION, TechLevel(level))
            val prospect = unresearched.withLevel(Technology.PROSPECTING, TechLevel(level))
            add(
                row(
                    "  level $level",
                    "drive ${frontierHold(home, hop, average, drive)} metal · " +
                        "prospecting ${frontierHold(home, hop, average, prospect)} metal",
                ),
            )
        }
    }

    // The two manifests each row compares, as pairs so the reading and its label cannot drift.
    private val EQUAL_BERTHS: Pair<Ships, Ships> =
        Ships.of(ShipType.SKIFF, 4) to Ships.of(ShipType.HAULER, 1)

    private val DESIGNS_POOL: Pair<Ships, Ships> =
        Ships.of(ShipType.SKIFF, 2) to Ships(mapOf(ShipType.HAULER to 1, ShipType.SKIFF to 2))

    // One rung, one pair, one sentence — including the two ways a rung can have no answer, which are
    // the ladder's own two states: neither manifest flies it, or only the fast one does.
    private fun pairing(
        target: GalaxyCoordinate,
        rung: kotlin.time.Duration,
        research: Research,
        sample: World,
        pair: Pair<Ships, Ships>,
    ): String {
        val (without, with) = pair
        val home = GalaxyState.initial(TEST_GALAXY_SEED).home
        val fits = { ships: Ships -> rung in FleetBalance.windowsFor(home, target, research, ships) }
        if (!fits(without)) return "neither flies it"
        val world = sample.copy(at = target)
        val bare = veinedHold(world, home, target, rung, without, research)
        if (!fits(with)) return "$bare without · the hauler cannot fly it"
        val loaded = veinedHold(world, home, target, rung, with, research)
        val delta = loaded - bare
        // **The clamp is the crossover.** A hauler buys hold, so it is worth nothing the moment the
        // *vein* rather than the window is what stops the run — which is why the answer moves with
        // the depth of the world and not only with the rung. Design's closing figure was measured on
        // a 1,798 vein where the skiffs alone strip it from 6h up; on a deep world the hauler goes on
        // paying at every rung it can fly. Saying which case a row is in is what makes the two
        // readings comparable at all.
        val cap = DepositBalance.cap(world, ResourceKind.METAL, FleetBalance.danger(home, world))
        val note = if (loaded >= cap) " · the vein, not the window" else ""
        return "$bare without · $loaded with · ${if (delta >= 0) "+" else ""}$delta to the hauler$note"
    }

    // What a manifest actually lands at a rung, clamped by the vein exactly as a run is — an
    // unclamped figure would credit the hauler for hold the world cannot supply, which is precisely
    // the crossover this section exists to locate.
    private fun veinedHold(
        world: World,
        home: GalaxyCoordinate,
        target: GalaxyCoordinate,
        rung: kotlin.time.Duration,
        ships: Ships,
        research: Research,
    ): Long {
        val station = FleetBalance.stationFor(home, target, rung, research, ships)
        val danger = FleetBalance.danger(home, world)
        val lift = FleetBalance.cargo(world, ResourceKind.METAL, ships, station, danger, research).metal
        return minOf(lift, DepositBalance.cap(world, ResourceKind.METAL, danger))
    }

    // Held at one richness on purpose — the generator has no positional gradient, so a far world is
    // *not* richer and reading these rows against a richer one would be reading a coincidence.
    private fun frontierHold(
        home: GalaxyCoordinate,
        target: GalaxyCoordinate,
        sample: World,
        research: Research = Research.initial(),
    ): Long {
        val station = FleetBalance.stationFor(home, target, 24.hours, research, FleetBalance.FASTEST_HULL)
        val world = sample.copy(at = target)
        return FleetBalance.cargo(
            world = world,
            gathering = ResourceKind.METAL,
            ships = Ships.of(ShipType.SKIFF, 1),
            station = station,
            danger = FleetBalance.danger(home, world),
            research = research,
        ).metal
    }

    // Clamped into the real map rather than offset blindly, so this reads the same whichever system
    // the doorstep clause put home in.
    private fun frontierTargets(home: GalaxyCoordinate): List<Pair<String, GalaxyCoordinate>> {
        val near = home.copy(system = (home.system + 60).coerceAtMost(GalaxyBalance.SYSTEMS_PER_GALAXY), slot = 1)
        val far = home.copy(system = if (home.system > GalaxyBalance.SYSTEMS_PER_GALAXY / 2) 1 else GalaxyBalance.SYSTEMS_PER_GALAXY, slot = 1)
        // **Adjacent**, not "any other galaxy" — the hop is priced per galaxy crossed, so a target two
        // galaxies out is 18h 20m of round trip and reads 0.42x at the 24h rung. That is a true number
        // about a different question, and printing it here would look like the frontier failing when
        // it is the second hop being a late-game undertaking exactly as the galaxy sheet intends.
        val other = home.copy(galaxy = if (home.galaxy == 1) 2 else home.galaxy - 1, slot = 1)
        return listOf(
            "the next slot" to home.copy(slot = if (home.slot == 1) 2 else 1),
            "60 systems out" to near,
            "across your own galaxy" to far,
            "the next galaxy" to other,
        )
    }

    // ── [horizon] where the curves actually put a colony at three months ────────────────────
    //
    // Davide, on the fortnight's numbers: *"56k on Metal in one week seems extreme, I would expect
    // that number in 3/4 months."* This section is that sentence turned into a measurement rather
    // than an argument — it says where the curves as they stand put a colony at one, two and three
    // months, so the question *how far off is this from what I wanted* has an answer with digits.
    //
    // It exists because a fortnight cannot answer it. A cost curve compounding at +50% against
    // production compounding at +25% flattens on its own, and how much it flattens is exactly what
    // decides whether the game needs re-scaling or a sink. Read `mine` against `metal`: the levels
    // slow down and the bank does not, which is the shape of a missing sink rather than a fast game.
    private fun horizon(): List<String> = buildList {
        val run = colony(days = HORIZON_DAYS)
        add("[horizon] the same fixed player, out to $HORIZON_DAYS days")
        add(row("day", "levels     mine   income/h         metal     placed"))
        for (day in listOf(7, 14, 30, 60, HORIZON_DAYS)) {
            val state = run.at(day * 24) ?: continue
            val levels = BuildingType.entries.sumOf { state.buildings.levelOf(it).value }
            var made = 0L
            var used = 0L
            for (hour in 0..(day * 24)) {
                val opened = run.arrivals[hour].resources.metal
                used += opened - run.states[hour].resources.metal
                if (hour > 0) made += opened - run.states[hour - 1].resources.metal
            }
            add(
                row(
                    "  day $day",
                    levels.toString().padStart(5) +
                        state.buildings.metalMine.value.toString().padStart(9) +
                        priced(income(state)).toString().padStart(11) +
                        state.resources.metal.toString().padStart(14) +
                        percent((used * 100 / maxOf(made, 1)).toInt(), 100).padStart(11),
                ),
            )
        }
        // **The cap is not decoration by day 90, it is the ceiling the colony is resting on.**
        // `STORAGE_CAPACITY` is a flat placeholder — its own comment calls the rule that raises it
        // (a storage building? mine-level-scaled?) an open question — and once a stock is against it
        // `advance` stops accruing, so every reading above understates: income past the cap is not
        // banked, not spent, and not earned. A page that printed 10,000,000 without saying it was
        // the ceiling would read as a big number rather than as a wall.
        val capped = run.states.count { it.resources.metal >= PlaceholderBalance.STORAGE_CAPACITY }
        add(row("hours resting on the metal storage cap", "${capped} of ${run.states.size}"))
        add(row("  first reached", hourText(run.firstHourWhere { it.resources.metal >= PlaceholderBalance.STORAGE_CAPACITY })))
    }

    // ── [late game] the wait a deep level asks for, and what the Nanite buys back ────────────
    //
    // Davide, 2026-08-11: *"I'd expect late game upgrade to be extremely slow, and expensive Nanite
    // upgrades to make them reasonable. I still think a late game upgrade could take various hours,
    // even with Nanite."* Three readings decide whether that is what the curves do — how slow it is
    // unaided, how much the Nanite gives back, and whether what is left is still hours.
    //
    // Read at Robotics 15, which is roughly where a colony stands once it is deep enough for any of
    // this to apply; the Robotics divisor is linear so the shape does not depend on the choice.
    private fun lateGame(): List<String> = buildList {
        add("[late game] metal mine wait at robotics 15, by nanite level")
        add(row("level", "nanite 0   nanite 2   nanite 4   nanite 6     0 -> 6  vs income"))
        for (level in listOf(16, 18, 20, 25, 30)) {
            val waits = listOf(0, 2, 4, 6).map {
                PlaceholderBalance.upgradeDuration(
                    BuildingType.METAL_MINE,
                    BuildingLevel(level),
                    BuildingLevel(15),
                    BuildingLevel(it),
                )
            }
            // The last column is the other half of the design: a deep level must outrun the income
            // that pays for it, which is the identity round 11 established for the mid-game and
            // 0.5.2 deliberately breaks above `LATE_GAME_FIRST_LEVEL`. Below the ramp it reads ~1.
            // **It is a column of this table rather than a second table** — two tables in one
            // section share their row labels, and the diff keys rows by `section + label`, so the
            // second would silently replace the first and half the section would never appear in a
            // review. `no two rows share a key` next door is the guard that found it.
            val cost = PlaceholderBalance.upgradeCost(BuildingType.METAL_MINE, BuildingLevel(level))
            val perHour = PlaceholderBalance.metalProductionPerHour(BuildingLevel(level - 1)) +
                PlaceholderBalance.crystalProductionPerHour(BuildingLevel(level - 1))
            val earning = (cost.metal + cost.crystal) * 60 / perHour
            val unaided = PlaceholderBalance
                .upgradeDuration(BuildingType.METAL_MINE, BuildingLevel(level), BuildingLevel(0), BuildingLevel(0))
                .inWholeMinutes
            add(
                row(
                    "  metal mine $level",
                    waits.joinToString("") { clock(it).padStart(11) } +
                        (ratio(waits.first().inWholeMinutes, waits.last().inWholeMinutes) + "x").padStart(11) +
                        (ratio(unaided, earning) + "x").padStart(11),
                ),
            )
        }
    }

    // ── the instruments ─────────────────────────────────────────────────────────────────────

    // One fixed player: every hour, buy the cheapest facility you can afford, then fill the research
    // slot with the cheapest project you can afford. Written out here rather than called into `:sim`
    // for the reason the two band files give — `core` cannot see the harness, and a page that
    // depended on the harness's strategy would be photographing the strategy.
    // Both halves of every hour, because the two answer different questions. `arrivals` is what the
    // check-in opens on — what the player is handed. `states` is what they leave behind. A reading
    // taken from the wrong one measures the buying policy instead of the balance.
    private class Run(val arrivals: List<GameState>, val states: List<GameState>) {

        fun at(hour: Int): GameState? = states.getOrNull(hour)

        fun firstHourWhere(predicate: (GameState) -> Boolean): Int? =
            states.indexOfFirst(predicate).takeIf { it >= 0 }
    }

    private fun colony(days: Int): Run {
        var state = GameState.initial(TEST_GALAXY_SEED)
        var now = EPOCH
        val arrivals = mutableListOf<GameState>()
        val states = mutableListOf<GameState>()
        for (hour in 0..(days * 24)) {
            val at = EPOCH + hour.hours
            state = advance(state, from = now, to = at)
            now = at
            arrivals += state
            state = spend(state, now)
            states += state
        }
        return Run(arrivals, states)
    }

    // The two caps are guarded rather than assumed: `upgradeCost` is only defined to level 40 and
    // `TechLevel` refuses anything past its own maximum, and a ninety-day run reaches neither in the
    // fortnight the rest of this page measures but would walk straight into both without this.
    private fun buyable(state: GameState, building: BuildingType): Boolean =
        next(state, building).value <= MAX_BUILDING_LEVEL

    private fun spend(from: GameState, now: Instant): GameState {
        var state = from
        for (building in OPENING_PLAN.filter { buyable(from, it) }
            .sortedBy { priced(PlaceholderBalance.upgradeCost(it, next(from, it))) }) {
            if (!buyable(state, building)) continue
            val cost = PlaceholderBalance.upgradeCost(building, next(state, building))
            if (!state.resources.covers(cost)) continue
            (startUpgrade(state, building, at = now) as? StartUpgradeResult.Started)?.let { state = it.state }
        }
        // Both branches, cheapest first, so the ladder is bought when it is the better buy rather
        // than because a policy preferred it. A benchmark that always pushed the applied branch
        // would never notice the adaptation branch drifting out of reach.
        //
        // **Up to two starts a visit since 0.12.2**, one per branch, because the slots are
        // independent. Still one pass in one order: the cheaper project is offered first whichever
        // branch it belongs to, and the loop ends the moment both slots are full rather than after
        // the first success.
        val applied = Technology.entries.filter { nextTech(state, it).value <= TechLevel.MAX }
            .map { it to priced(ResearchBalance.researchCost(it, nextTech(state, it))) }
        val ladders = AdaptationTechnology.entries.filter { nextTech(state, it).value <= TechLevel.MAX }
            .map { it to priced(AdaptationBalance.adaptationCost(it, nextTech(state, it))) }
        for ((project, _) in (applied + ladders).sortedBy { it.second }) {
            val started = when (project) {
                is Technology -> (startResearch(state, project, at = now) as? StartResearchResult.Started)?.state
                is AdaptationTechnology -> (startAdaptation(state, project, at = now) as? StartAdaptationResult.Started)?.state
                else -> null
            }
            if (started != null) state = started
            if (state.activeResearch != null && state.activeAdaptation != null) return state
        }
        return state
    }

    // The first hour at one-minute resolution — the only cadence that can tell a two-minute build
    // from a fifty-minute one.
    private fun firstSitting(): List<Int> {
        var state = GameState.initial(TEST_GALAXY_SEED)
        var now = EPOCH
        var seen = 0
        return buildList {
            for (minute in 0..60) {
                val at = EPOCH + minute.minutes
                state = advance(state, from = now, to = at)
                now = at
                repeat(state.eventLog.drop(seen).count { it.isCompletion() }) { add(minute) }
                seen = state.eventLog.size
                state = spend(state, now)
            }
        }
    }

    private class Visit(val finished: Int, val affordable: Int, val kinds: Int, val running: Int)

    // Davide's own cadence, from `printOpeningReport`: morning, lunch, evening, bedtime.
    private fun checkIns(days: Int): List<Visit> {
        var state = GameState.initial(TEST_GALAXY_SEED)
        var now = EPOCH
        var seen = 0
        return buildList {
            for (day in 0 until days) {
                for (hour in listOf(8, 13, 19, 23)) {
                    val at = EPOCH + (day * 24 + hour).hours
                    state = advance(state, from = now, to = at)
                    now = at
                    val finished = state.eventLog.drop(seen).count { it.isCompletion() }
                    seen = state.eventLog.size
                    val buildings = OPENING_PLAN.count { state.resources.covers(PlaceholderBalance.upgradeCost(it, next(state, it))) }
                    val projects = offeredProjects(state)
                    state = spend(state, now)
                    add(
                        Visit(
                            finished = finished,
                            affordable = buildings + projects,
                            kinds = listOf(buildings > 0, projects > 0).count { it },
                            running = state.builds.size,
                        ),
                    )
                }
            }
        }
    }

    // Counted per branch, because the slots are independent: a project running refuses the other
    // three applied rows and says nothing at all about the three ladders.
    private fun offeredProjects(state: GameState): Int {
        val applied = if (state.activeResearch != null) {
            0
        } else {
            Technology.entries.count {
                ResearchBalance.requirementFor(it).isMetBy(state) &&
                    state.resources.covers(ResearchBalance.researchCost(it, nextTech(state, it)))
            }
        }
        val ladders = if (state.activeAdaptation != null) {
            0
        } else {
            AdaptationTechnology.entries.count {
                AdaptationBalance.requirementFor(it).isMetBy(state) &&
                    state.resources.covers(AdaptationBalance.adaptationCost(it, nextTech(state, it)))
            }
        }
        return applied + ladders
    }

    private fun wholeGalaxy(): List<World> = buildList {
        for (galaxy in 1..GalaxyBalance.GALAXIES) {
            for (system in 1..GalaxyBalance.SYSTEMS_PER_GALAXY) {
                for (slot in 1..GalaxyBalance.SLOTS_PER_SYSTEM) {
                    worldAt(TEST_GALAXY_SEED, GalaxyCoordinate(galaxy, system, slot))?.let(::add)
                }
            }
        }
    }

    // A *completion* is what a player watches; a start is what they did. The event log holds both,
    // and counting the pair would double every reading here.
    private fun Event.isCompletion(): Boolean = when (this) {
        is Event.BuildCompleted, is Event.ResearchCompleted, is Event.AdaptationCompleted,
        is Event.SurveyCompleted, is Event.FleetReturned,
        -> true
        else -> false
    }

    private fun income(state: GameState): Resources = Resources.of(
        metal = PlaceholderBalance.effectiveMetalProductionPerHour(state.buildings, state.research),
        crystal = PlaceholderBalance.effectiveCrystalProductionPerHour(state.buildings, state.research),
        deuterium = PlaceholderBalance.effectiveDeuteriumProductionPerHour(state.buildings, state.research),
    )

    // What the level itself adds, priced — the denominator of payback. Zero for a facility that
    // raises no rate, which is why the Robotics Factory and the Solar Plant read "-" rather than a
    // misleading infinity.
    private fun incomeGain(building: BuildingType, level: Int): Long {
        val at = { l: Int -> Buildings.initial().withLevel(building, BuildingLevel(l)) }
        fun rate(l: Int): Long = priced(
            Resources.of(
                metal = PlaceholderBalance.metalProductionPerHour(at(l).metalMine),
                crystal = PlaceholderBalance.crystalProductionPerHour(at(l).crystalMine),
                deuterium = PlaceholderBalance.deuteriumProductionPerHour(at(l).deuteriumSynthesizer),
            ),
        )
        return rate(level) - rate(level - 1)
    }

    // What the technology adds to *this* colony's priced income, which is the only honest
    // denominator: a multiplier's worth depends entirely on the rate it multiplies.
    //
    // Always level-1 against level, never against whatever the colony happens to hold. The first
    // draft compared level 1 to the *current* state and produced a negative gain — a "-" in the
    // payback column — for every technology the day-3 colony had already pushed past, which reads
    // as "this level never pays for itself" and means nothing of the sort.
    //
    // A genuine "-" survives, and Photovoltaics shows one at every level: it raises supply, the
    // colony is in surplus, and a multiplier on a term nothing is dividing by buys exactly nothing.
    // That is the branch's own shape rather than an artefact — the technology is insurance against a
    // deficit, and a page that hid it would be hiding the most interesting row on it.
    private fun researchGain(state: GameState, technology: Technology, level: Int): Long {
        fun at(value: Int): Long =
            priced(income(state.copy(research = state.research.withLevel(technology, TechLevel(value)))))
        return at(level) - at(level - 1)
    }

    private fun next(state: GameState, building: BuildingType): BuildingLevel =
        BuildingLevel(state.buildings.levelOf(building).value + 1)

    private fun nextTech(state: GameState, technology: Technology): TechLevel =
        TechLevel(state.research.levelOf(technology).value + 1)

    private fun nextTech(state: GameState, technology: AdaptationTechnology): TechLevel =
        TechLevel(state.research.levelOf(technology).value + 1)

    private fun priced(resources: Resources): Long =
        resources.metal + 2 * resources.crystal + 3 * resources.deuterium

    private fun longestGap(landings: List<Int>, upTo: Int): Int =
        (listOf(0) + landings.sorted() + listOf(upTo)).zipWithNext { a, b -> b - a }.maxOrNull() ?: upTo

    private fun List<Int>.median(): Int = if (isEmpty()) 0 else sorted()[size / 2]

    // ── formatting, which is load-bearing: a golden is only useful if its diff is readable ──

    private fun StringBuilder.section(lines: List<String>) {
        appendLine()
        lines.forEach { appendLine(it) }
    }

    // `require` rather than a silent trim: a row padded to a value that is not there leaves
    // invisible trailing spaces, an editor strips them on the next save, and the golden then
    // fails for a reason that is not visible anywhere in the diff. A section header with no
    // value is a plain line, not a row.
    private fun row(label: String, value: String): String {
        require(value.isNotEmpty()) { "a row needs a value; '$label' should be a plain line" }
        return label.padEnd(ROW_WIDTH) + value
    }

    private fun hourText(hour: Int?): String = if (hour == null) "not within the run" else "hour $hour (day ${hour / 24})"

    private fun clock(duration: Duration): String {
        val minutes = duration.inWholeMinutes
        return if (minutes < 60) "${minutes}m" else "${minutes / 60}h ${(minutes % 60).toString().padStart(2, '0')}m"
    }

    // Two decimals, by integer arithmetic. `core` is pure and compiles for Kotlin/Native as well as
    // the JVM, and a float here could render a different last digit on one target than the other —
    // which would make the golden fail on a platform rather than on a change.
    private fun ratio(numerator: Long, denominator: Long): String {
        if (denominator == 0L) return "-"
        val hundredths = numerator * 100 / denominator
        return "${hundredths / 100}.${(hundredths % 100).toString().padStart(2, '0')}"
    }

    private fun percent(part: Int, whole: Int): String = percent(part.toLong(), whole.toLong())

    private fun percent(part: Long, whole: Long): String {
        if (whole == 0L) return "-"
        val hundredths = part * 10_000 / whole
        return "${hundredths / 100}.${(hundredths % 100).toString().padStart(2, '0')}%"
    }

    private fun label(building: BuildingType): String = building.name.lowercase().replace('_', ' ')

    private fun label(technology: Technology): String = technology.name.lowercase()

    private fun label(technology: AdaptationTechnology): String = technology.name.lowercase()

    private fun label(axis: HostilityAxis): String = axis.name.lowercase()

    private val EPOCH: Instant = Instant.fromEpochMilliseconds(0)

    private const val ROW_WIDTH: Int = 50

    // Two weeks, because one is not long enough to show progression flattening and a month makes
    // this page slower than every other test in the module put together.
    private const val LONG_HORIZON_DAYS: Int = 14

    // A quarter, because that is the unit the question was asked in. It is the most expensive figure
    // on the page — 2,161 hourly steps — and still cheap next to the galaxy sweep above it.
    private const val HORIZON_DAYS: Int = 90

    // `PlaceholderBalance.upgradeCost` is only defined this deep; past it the curve leaves Long.
    private const val MAX_BUILDING_LEVEL: Int = 40

    // Enough for a share to be stable to about a point; genesis walks its galaxy once per seed, so
    // this is the most expensive figure on the page.
    private const val BENCHMARK_SEEDS: Int = 100

    // **Every facility, and the Nanite Factory belongs here again as of 0.5.2.**
    //
    // It was taken out one round ago because it did nothing — no curve read `buildings.naniteFactory`,
    // so a player who bought it was strictly worse off and a benchmark that bought it flattered the
    // metal pile by spending on a row that bought nothing. Davide asked what it was for, and the
    // answer was the change: it is now the only thing that shortens a late-game build, so the fixed
    // player buys it for the same reason a real one would.
    //
    // This is the note the previous round asked for, honoured: *"when the Nanite Factory is given an
    // effect, it belongs back in this list and the golden will move to say so."* Leaving it out now
    // would understate the late game exactly as including it once overstated the mid-game — the
    // colony would meet the `LATE_GAME_FIRST_LEVEL` ramp with no answer to it, and `[horizon]` would
    // photograph a wall no real player would stand in front of.
    private val OPENING_PLAN = listOf(
        BuildingType.METAL_MINE,
        BuildingType.CRYSTAL_MINE,
        BuildingType.DEUTERIUM_SYNTHESIZER,
        BuildingType.SOLAR_PLANT,
        BuildingType.ROBOTICS_FACTORY,
        BuildingType.NANITE_FACTORY,
    )
}
