package dev.fardavide.oltre.core

import kotlin.time.Duration
import kotlin.time.Duration.Companion.hours
import kotlin.time.Duration.Companion.minutes
import kotlin.time.Instant

// **The whole balance surface, rendered as one deterministic page.**
//
// `OpeningBalanceTest` and `CheckInBalanceTest` are *bands* — they fail when the opening leaves the
// shape it is meant to have, and they deliberately say nothing while it moves inside that shape.
// That is the right instrument for a guardrail and the wrong one for a review, because the readings
// a band lets through are exactly the ones a designer wants to see before agreeing to them.
//
// So this is the other instrument: not an assertion about the balance but a **photograph** of it.
// `BalanceBenchmarkTest` compares this page against `BalanceBenchmarkGolden`, a plain string in the
// file next door, and the golden is committed. The consequence is the point —
//
//   **a change to any balance number shows up as a diff on a page of player-visible readings, in
//   the pull request, whether or not any band was crossed.**
//
// 0.5.1 is the case it is built for. That change moved the gate from Robotics 4 to Robotics 2 and
// re-homed every new colony, every test in the repository passed, and the review had nothing in
// front of it but prose. With this page, the same change arrives as thirty moved lines — the gate
// clock going 33h to 12h, the doorstep going 5 levels to 1, the research refusals trading places
// with the price refusals — and a reviewer can agree or disagree with the *effect* rather than with
// an argument about a constant.
//
// ── Reading it ───────────────────────────────────────────────────────────────────────────────
//
// Everything here is derived, never a constant copied out. A row that just restated
// `AdaptationBalance.GATE` would move when the constant moved and tell a reviewer nothing they did
// not already see in the diff; a row that says *what hour the branch opens* moves when the gate
// moves **and** when the build curve, the discount, the Robotics divisor or the opening stock move,
// which is the whole reason the page exists.
//
// The simulated colony is one player, played one way — every hour, buy the cheapest thing you can
// afford. It is not a good player and is not meant to be. It is a *fixed* player, so that a
// difference between two runs of this page is a difference in the game rather than in the strategy.
internal object BalanceBenchmark {

    // `trimEnd` because the golden next door is a `trimIndent`ed raw string, and `trimIndent`
    // drops the blank line before the closing quotes. Without this the two would differ by one
    // invisible character and the page would never match on any target.
    fun render(): String = buildString {
        appendLine("# Oltre balance benchmark")
        appendLine("#")
        appendLine("# Generated by BalanceBenchmarkTest from the balance objects in :core.")
        appendLine("# Every reading is derived. Do not hand-edit — regenerate and read the diff.")
        appendLine("#")
        appendLine("# The colony below checks in every hour and buys the cheapest thing it can")
        appendLine("# afford, buildings first, then whichever research project is cheapest. One")
        appendLine("# fixed player, so a diff on this page is a change to the game.")
        section(opening())
        section(session())
        section(progression())
        section(pressure())
        section(economy())
        section(research())
        section(adaptation())
        section(galaxy())
        section(fleet())
    }.trimEnd()

    // ── [opening] the landmarks, as a clock ──────────────────────────────────────────────────
    //
    // Every gate in the game is a Robotics Factory level, so the branch that opens on a level is
    // only as far away as the level is. These rows are what Davide's *"I needed 2 day to get
    // robotics to level 4"* reads as when the game says it rather than a player.
    private fun opening(): List<String> = buildList {
        val run = colony(days = LONG_HORIZON_DAYS)
        add("[opening] the hour each landmark lands, for a colony that checks in hourly")
        for (level in listOf(1, 2, 4, 9, 10)) {
            add(row("robotics factory $level", hourText(run.firstHourWhere { it.buildings.roboticsFactory.value >= level })))
        }
        add(row("mines past the opening discount (level 9)", hourText(run.firstHourWhere { it.buildings.metalMine.value >= 9 })))
        add(row("first applied technology finished", hourText(run.firstHourWhere { state -> Technology.entries.any { state.research.levelOf(it).value >= 1 } })))
        add(row("first adaptation level finished", hourText(run.firstHourWhere { state -> AdaptationTechnology.entries.any { state.research.levelOf(it).value >= 1 } })))
        add(row("second skiff affordable", hourText(run.firstHourWhere { it.resources.covers(FleetBalance.shipCost(ShipType.SKIFF, 1)) })))
    }

    // ── [session] what five minutes of the game holds ────────────────────────────────────────
    //
    // Round 16's readings, which is the round Davide asked for *"some adrenaline"* in. A build curve
    // that gets slower shows up here before it shows up anywhere else.
    private fun session(): List<String> = buildList {
        val landings = firstSitting()
        add("[session] completions a player is present for, minute by minute")
        add(row("first completion", if (landings.isEmpty()) "never" else "minute ${landings.min()}"))
        for (window in listOf(10, 30, 60)) {
            add(row("completions within $window min", "${landings.count { it <= window }}"))
        }
        add(row("longest silence in the first 15 min", "${longestGap(landings.filter { it <= 15 }, upTo = 15)}m"))
        add(row("longest silence in the first hour", "${longestGap(landings, upTo = 60)}m"))

        val visits = checkIns(days = 2)
        add(row("dead check-ins in the first two days", "${visits.count { it.finished == 0 && it.affordable == 0 }} of ${visits.size}"))
        add(row("check-ins offering two kinds of decision", "${visits.count { it.kinds >= 2 }} of ${visits.size}"))
        add(row("check-ins leaving work booked", "${visits.count { it.running > 0 }} of ${visits.size}"))
    }

    // ── [progression] is the colony still moving ─────────────────────────────────────────────
    private fun progression(): List<String> = buildList {
        val run = colony(days = LONG_HORIZON_DAYS)
        add("[progression] where the colony stands, day by day")
        // **Banked is split three ways rather than priced into one figure**, because the lopsided
        // bank is the failure this row exists to show and pricing hides it perfectly: round 7 found
        // a colony closing a week on 49,544 metal it had nothing to spend on against 1,410 crystal,
        // and a single priced total would have called that a healthy 52,364.
        add(row("day", "levels   income/h        metal    crystal      deut"))
        for (day in listOf(1, 2, 3, 7, 14)) {
            val state = run.at(day * 24) ?: continue
            val levels = BuildingType.entries.sumOf { state.buildings.levelOf(it).value }
            add(
                row(
                    "  day $day",
                    levels.toString().padStart(5) +
                        priced(income(state)).toString().padStart(11) +
                        state.resources.metal.toString().padStart(13) +
                        state.resources.crystal.toString().padStart(11) +
                        state.resources.deuterium.toString().padStart(10),
                ),
            )
        }
    }

    // ── [pressure] which resource is the one saying no ───────────────────────────────────────
    //
    // Round 7's whole subject, and the reading that caught the 3:1 metal-to-crystal ratio being
    // wrong in 0.1.0 — a colony closing a week on 49,544 metal it had nothing to spend on. A
    // production-ratio change that leaves every curve's shape intact lands here and nowhere else.
    private fun pressure(): List<String> = buildList {
        val run = colony(days = LONG_HORIZON_DAYS)
        var blocked = 0
        val short = mutableMapOf<String, Int>()
        // **Read on arrival, before the colony spends.** Measured after spending, this section says
        // 99.4% and means nothing at all: a greedy player empties the bank every hour by
        // construction, so "can it afford the next row" is answered by the policy rather than by the
        // economy. What a player actually meets is the state the *check-in opens on*, which is the
        // state `advance` hands back before anything is bought.
        for (state in run.arrivals) {
            val cheapest = OPENING_PLAN
                .map { PlaceholderBalance.upgradeCost(it, next(state, it)) }
                .minByOrNull { priced(it) } ?: continue
            if (state.resources.covers(cheapest)) continue
            blocked++
            if (state.resources.metal < cheapest.metal) short["metal"] = (short["metal"] ?: 0) + 1
            if (state.resources.crystal < cheapest.crystal) short["crystal"] = (short["crystal"] ?: 0) + 1
            if (state.resources.deuterium < cheapest.deuterium) short["deuterium"] = (short["deuterium"] ?: 0) + 1
        }
        // Idleness is the opposite: it is a property of what the colony was *left* holding, so it is
        // read after the spend. Round 16 called this the biggest open item in the balance log.
        val idle = run.states.count { it.builds.isEmpty() && it.researchSlotFreesAt == null }
        add("[pressure] over $LONG_HORIZON_DAYS days, which resource blocks the cheapest unbuilt row")
        add(row("hours opening with the cheapest row unaffordable", percent(blocked, run.arrivals.size)))
        for (kind in listOf("metal", "crystal", "deuterium")) {
            add(row("  of which short of $kind", percent(short[kind] ?: 0, maxOf(blocked, 1))))
        }
        add(row("hours with nothing building and no research", percent(idle, run.states.size)))
    }

    // ── [economy] what a level costs and what it gives back ──────────────────────────────────
    //
    // Payback is the reading round 11 was argued from — cost compounds at +50% and output at +25%,
    // so payback grows with depth *by design*, and the question a benchmark has to answer is how
    // fast. A curve change that keeps both shapes and moves their relationship shows up in this
    // column and in no assertion anywhere.
    private fun economy(): List<String> = buildList {
        add("[economy] cost, wait and payback per level, at robotics factory 4")
        add(row("building / level", "priced    build     +income/h   payback"))
        for (building in OPENING_PLAN) {
            for (level in listOf(1, 5, 10, 20)) {
                val cost = PlaceholderBalance.upgradeCost(building, BuildingLevel(level))
                val wait = PlaceholderBalance.upgradeDuration(building, BuildingLevel(level), BuildingLevel(4))
                val gain = incomeGain(building, level)
                add(
                    row(
                        "  ${label(building)} $level",
                        priced(cost).toString().padStart(9) +
                            clock(wait).padStart(9) +
                            (if (gain == 0L) "-" else gain.toString()).padStart(12) +
                            (if (gain == 0L) "-" else ratio(priced(cost), gain) + "h").padStart(10),
                    ),
                )
            }
        }
        val day2 = checkNotNull(colony(days = 2).at(48))
        val energy = PlaceholderBalance.energyBalance(day2.buildings, day2.research)
        add(row("day-2 colony energy", "${energy.produced} produced / ${energy.consumed} consumed"))
        add(row("day-2 colony energy headroom", "${PlaceholderBalance.energyHeadroomLevels(day2.buildings, day2.research)} levels"))
    }

    // ── [research] the applied branch, and whether a level is ever worth the slot ────────────
    private fun research(): List<String> = buildList {
        val day3 = checkNotNull(colony(days = 3).at(72))
        add("[research] cost, wait and effect per level, at robotics factory 4")
        add(row("technology / level", "priced    wait      effect   payback"))
        for (technology in Technology.entries) {
            for (level in 1..5) {
                val cost = ResearchBalance.researchCost(technology, TechLevel(level))
                val wait = ResearchBalance.researchDuration(technology, TechLevel(level), BuildingLevel(4))
                val effect = ResearchBalance.effectPercent(technology, TechLevel(level))
                val gain = researchGain(day3, technology, level)
                add(
                    row(
                        "  ${label(technology)} $level",
                        priced(cost).toString().padStart(9) +
                            clock(wait).padStart(10) +
                            "+$effect%".padStart(9) +
                            (if (gain <= 0L) "-" else ratio(priced(cost), gain) + "h").padStart(10),
                    ),
                )
            }
        }
    }

    // ── [adaptation] the second branch, priced against the first ────────────────────────────
    //
    // The two branches share one empire-wide slot, so what matters is not either table but the
    // **ratio** between them: the adaptation sheet's argument for 4,800 is that a ladder level costs
    // about twice the priciest applied technology. A discount that reached one branch and not the
    // other broke that once already, at 5.8x, and this row is where that would have been visible.
    private fun adaptation(): List<String> = buildList {
        add("[adaptation] cost and wait per level, at the gate's own robotics level")
        val gate = AdaptationBalance.GATE
        add(row("ladder / level", "priced    wait      x priciest applied"))
        for (ladder in AdaptationTechnology.entries) {
            for (level in 1..5) {
                val cost = AdaptationBalance.adaptationCost(ladder, TechLevel(level))
                val wait = AdaptationBalance.adaptationDuration(ladder, TechLevel(level), gate)
                val dearest = Technology.entries.maxOf { priced(ResearchBalance.researchCost(it, TechLevel(level))) }
                add(
                    row(
                        "  ${label(ladder)} $level",
                        priced(cost).toString().padStart(9) +
                            clock(wait).padStart(10) +
                            ratio(priced(cost), dearest).padStart(20),
                    ),
                )
            }
        }
    }

    // ── [galaxy] the map, and what a ladder level buys on it ────────────────────────────────
    //
    // The galaxy-wide rows are what `GalaxyDistributionTest` asserts; they are reproduced here
    // because the doorstep rows underneath them are meaningless without the distribution they sit
    // in. **The doorstep rows are the ones 0.5.1 shipped without** — a whole-galaxy statistic said
    // an adaptation level roughly doubles the settleable count, and a player standing in one system
    // met a wall, because a colony's sample is its own home system and nothing else.
    private fun galaxy(): List<String> = buildList {
        val worlds = wholeGalaxy()
        val unaided = GalaxyBalance.tolerance(AdaptationLevels.NONE)
        add("[galaxy] the map as generated, from seed ${TEST_GALAXY_SEED.value}")
        add(row("worlds in the coordinate space", "${worlds.size} of ${GalaxyBalance.TOTAL_SLOTS} slots"))
        for (axis in HostilityAxis.entries) {
            add(row("  ${label(axis)} band passes", percent(worlds.count { it.traits.axisValue(axis) in unaided.bandOf(axis) }, worlds.size)))
        }
        add(row("  passes every band", percent(worlds.count { world -> HostilityAxis.entries.all { world.traits.axisValue(it) in unaided.bandOf(it) } }, worlds.size)))
        add(row("settleable at adaptation level", "count    share"))
        for (level in listOf(0, 1, 2, 3, 4, 6)) {
            val tolerance = GalaxyBalance.tolerance(AdaptationLevels(level, level, level))
            val settleable = worlds.count { world ->
                HostilityAxis.entries.all { world.traits.axisValue(it) in tolerance.bandOf(it) } &&
                    GalaxyBalance.yieldScore(world.traits).perMillion >= GalaxyBalance.WORTH_IT_THRESHOLD.perMillion
            }
            add(row("  all three ladders at $level", settleable.toString().padStart(5) + percent(settleable, worlds.size).padStart(9)))
        }

        val openings = (0 until BENCHMARK_SEEDS).map { offset ->
            val seed = GalaxySeed(TEST_GALAXY_SEED.value + offset)
            val state = GalaxyState.initial(seed)
            state.surveyed.filter { it != state.home }
                .mapNotNull { worldAt(seed, it) }
                .map { GalaxyBalance.levelsToTolerate(it.traits) }
                .sorted()
        }
        add("[galaxy] the opening screen, over $BENCHMARK_SEEDS colonies")
        add(row("non-home worlds on the screen, median", "${openings.map { it.size }.median()}"))
        for ((index, name) in listOf("cheapest", "second", "third").withIndex()) {
            add(row("  $name neighbour, levels away, median", "${openings.mapNotNull { it.getOrNull(index) }.median()}"))
        }
        add(row("colonies with a neighbour at one level", percent(openings.count { (it.firstOrNull() ?: 99) <= 1 }, openings.size)))
        add(row("colonies with every neighbour blocked", percent(openings.count { it.isNotEmpty() && it.all { levels -> levels > 0 } }, openings.size)))
    }

    // ── [fleet] the hull curve, and when the second one lands ───────────────────────────────
    private fun fleet(): List<String> = buildList {
        add("[fleet] the hull curve and one representative run")
        for (owned in 0 until 5) {
            val cost = FleetBalance.shipCost(ShipType.SKIFF, owned)
            add(row("  skiff ${owned + 1}", "${cost.metal} metal / ${cost.crystal} crystal, priced ${priced(cost)}"))
        }
        val home = GalaxyState.initial(TEST_GALAXY_SEED).home
        val neighbour = home.copy(slot = if (home.slot == 1) 2 else 1)
        val window = 6.hours
        add(row("6h run to the next slot, round trip", clock(FleetBalance.roundTrip(home, neighbour))))
        add(row("  station time", clock(FleetBalance.stationFor(home, neighbour, window))))
        val average = World(
            at = neighbour,
            starClass = StarClass.STANDARD,
            traits = worldAt(TEST_GALAXY_SEED, home)?.traits ?: error("home has no world"),
        )
        val cargo = FleetBalance.cargo(
            world = average,
            gathering = ResourceKind.METAL,
            ships = Ships.of(ShipType.SKIFF, 1),
            station = FleetBalance.stationFor(home, neighbour, window),
            danger = 0,
        )
        add(row("  one skiff brings home", "${cargo.metal} metal"))
        add(row("  as hours of a genesis colony's metal", ratio(cargo.metal, PlaceholderBalance.metalProductionPerHour(BuildingLevel(1))) + "h"))
    }

    // ── the instruments ─────────────────────────────────────────────────────────────────────

    // One fixed player: every hour, buy the cheapest facility you can afford, then fill the research
    // slot with the cheapest project you can afford. Written out here rather than called into `:sim`
    // for the reason the two band files give — `core` cannot see the harness, and a page that
    // depended on the harness's strategy would be photographing the strategy.
    // Both halves of every hour, because the two answer different questions. `arrivals` is what the
    // check-in opens on — what the player is handed. `states` is what they leave behind. A reading
    // taken from the wrong one measures the buying policy instead of the balance.
    private class Run(val arrivals: List<GameState>, val states: List<GameState>) {

        fun at(hour: Int): GameState? = states.getOrNull(hour)

        fun firstHourWhere(predicate: (GameState) -> Boolean): Int? =
            states.indexOfFirst(predicate).takeIf { it >= 0 }
    }

    private fun colony(days: Int): Run {
        var state = GameState.initial(TEST_GALAXY_SEED)
        var now = EPOCH
        val arrivals = mutableListOf<GameState>()
        val states = mutableListOf<GameState>()
        for (hour in 0..(days * 24)) {
            val at = EPOCH + hour.hours
            state = advance(state, from = now, to = at)
            now = at
            arrivals += state
            state = spend(state, now)
            states += state
        }
        return Run(arrivals, states)
    }

    private fun spend(from: GameState, now: Instant): GameState {
        var state = from
        for (building in OPENING_PLAN.sortedBy { priced(PlaceholderBalance.upgradeCost(it, next(from, it))) }) {
            val cost = PlaceholderBalance.upgradeCost(building, next(state, building))
            if (!state.resources.covers(cost)) continue
            (startUpgrade(state, building, at = now) as? StartUpgradeResult.Started)?.let { state = it.state }
        }
        if (state.researchSlotFreesAt != null) return state
        // Both branches, cheapest first, so the ladder is bought when it is the better buy rather
        // than because a policy preferred it. A benchmark that always pushed the applied branch
        // would never notice the adaptation branch drifting out of reach.
        val applied = Technology.entries.map { it to priced(ResearchBalance.researchCost(it, nextTech(state, it))) }
        val ladders = AdaptationTechnology.entries.map { it to priced(AdaptationBalance.adaptationCost(it, nextTech(state, it))) }
        for ((project, _) in (applied + ladders).sortedBy { it.second }) {
            val started = when (project) {
                is Technology -> (startResearch(state, project, at = now) as? StartResearchResult.Started)?.state
                is AdaptationTechnology -> (startAdaptation(state, project, at = now) as? StartAdaptationResult.Started)?.state
                else -> null
            }
            if (started != null) return started
        }
        return state
    }

    // The first hour at one-minute resolution — the only cadence that can tell a two-minute build
    // from a fifty-minute one.
    private fun firstSitting(): List<Int> {
        var state = GameState.initial(TEST_GALAXY_SEED)
        var now = EPOCH
        var seen = 0
        return buildList {
            for (minute in 0..60) {
                val at = EPOCH + minute.minutes
                state = advance(state, from = now, to = at)
                now = at
                repeat(state.eventLog.drop(seen).count { it.isCompletion() }) { add(minute) }
                seen = state.eventLog.size
                state = spend(state, now)
            }
        }
    }

    private class Visit(val finished: Int, val affordable: Int, val kinds: Int, val running: Int)

    // Davide's own cadence, from `printOpeningReport`: morning, lunch, evening, bedtime.
    private fun checkIns(days: Int): List<Visit> {
        var state = GameState.initial(TEST_GALAXY_SEED)
        var now = EPOCH
        var seen = 0
        return buildList {
            for (day in 0 until days) {
                for (hour in listOf(8, 13, 19, 23)) {
                    val at = EPOCH + (day * 24 + hour).hours
                    state = advance(state, from = now, to = at)
                    now = at
                    val finished = state.eventLog.drop(seen).count { it.isCompletion() }
                    seen = state.eventLog.size
                    val buildings = OPENING_PLAN.count { state.resources.covers(PlaceholderBalance.upgradeCost(it, next(state, it))) }
                    val projects = offeredProjects(state)
                    state = spend(state, now)
                    add(
                        Visit(
                            finished = finished,
                            affordable = buildings + projects,
                            kinds = listOf(buildings > 0, projects > 0).count { it },
                            running = state.builds.size,
                        ),
                    )
                }
            }
        }
    }

    private fun offeredProjects(state: GameState): Int {
        if (state.researchSlotFreesAt != null) return 0
        val applied = Technology.entries.count {
            ResearchBalance.requirementFor(it).isMetBy(state) &&
                state.resources.covers(ResearchBalance.researchCost(it, nextTech(state, it)))
        }
        val ladders = AdaptationTechnology.entries.count {
            AdaptationBalance.requirementFor(it).isMetBy(state) &&
                state.resources.covers(AdaptationBalance.adaptationCost(it, nextTech(state, it)))
        }
        return applied + ladders
    }

    private fun wholeGalaxy(): List<World> = buildList {
        for (galaxy in 1..GalaxyBalance.GALAXIES) {
            for (system in 1..GalaxyBalance.SYSTEMS_PER_GALAXY) {
                for (slot in 1..GalaxyBalance.SLOTS_PER_SYSTEM) {
                    worldAt(TEST_GALAXY_SEED, GalaxyCoordinate(galaxy, system, slot))?.let(::add)
                }
            }
        }
    }

    // A *completion* is what a player watches; a start is what they did. The event log holds both,
    // and counting the pair would double every reading here.
    private fun Event.isCompletion(): Boolean = when (this) {
        is Event.BuildCompleted, is Event.ResearchCompleted, is Event.AdaptationCompleted,
        is Event.SurveyCompleted, is Event.FleetReturned,
        -> true
        else -> false
    }

    private fun income(state: GameState): Resources = Resources.of(
        metal = PlaceholderBalance.effectiveMetalProductionPerHour(state.buildings, state.research),
        crystal = PlaceholderBalance.effectiveCrystalProductionPerHour(state.buildings, state.research),
        deuterium = PlaceholderBalance.effectiveDeuteriumProductionPerHour(state.buildings, state.research),
    )

    // What the level itself adds, priced — the denominator of payback. Zero for a facility that
    // raises no rate, which is why the Robotics Factory and the Solar Plant read "-" rather than a
    // misleading infinity.
    private fun incomeGain(building: BuildingType, level: Int): Long {
        val at = { l: Int -> Buildings.initial().withLevel(building, BuildingLevel(l)) }
        fun rate(l: Int): Long = priced(
            Resources.of(
                metal = PlaceholderBalance.metalProductionPerHour(at(l).metalMine),
                crystal = PlaceholderBalance.crystalProductionPerHour(at(l).crystalMine),
                deuterium = PlaceholderBalance.deuteriumProductionPerHour(at(l).deuteriumSynthesizer),
            ),
        )
        return rate(level) - rate(level - 1)
    }

    // What the technology adds to *this* colony's priced income, which is the only honest
    // denominator: a multiplier's worth depends entirely on the rate it multiplies.
    //
    // Always level-1 against level, never against whatever the colony happens to hold. The first
    // draft compared level 1 to the *current* state and produced a negative gain — a "-" in the
    // payback column — for every technology the day-3 colony had already pushed past, which reads
    // as "this level never pays for itself" and means nothing of the sort.
    //
    // A genuine "-" survives, and Photovoltaics shows one at every level: it raises supply, the
    // colony is in surplus, and a multiplier on a term nothing is dividing by buys exactly nothing.
    // That is the branch's own shape rather than an artefact — the technology is insurance against a
    // deficit, and a page that hid it would be hiding the most interesting row on it.
    private fun researchGain(state: GameState, technology: Technology, level: Int): Long {
        fun at(value: Int): Long =
            priced(income(state.copy(research = state.research.withLevel(technology, TechLevel(value)))))
        return at(level) - at(level - 1)
    }

    private fun next(state: GameState, building: BuildingType): BuildingLevel =
        BuildingLevel(state.buildings.levelOf(building).value + 1)

    private fun nextTech(state: GameState, technology: Technology): TechLevel =
        TechLevel(state.research.levelOf(technology).value + 1)

    private fun nextTech(state: GameState, technology: AdaptationTechnology): TechLevel =
        TechLevel(state.research.levelOf(technology).value + 1)

    private fun priced(resources: Resources): Long =
        resources.metal + 2 * resources.crystal + 3 * resources.deuterium

    private fun longestGap(landings: List<Int>, upTo: Int): Int =
        (listOf(0) + landings.sorted() + listOf(upTo)).zipWithNext { a, b -> b - a }.maxOrNull() ?: upTo

    private fun List<Int>.median(): Int = if (isEmpty()) 0 else sorted()[size / 2]

    // ── formatting, which is load-bearing: a golden is only useful if its diff is readable ──

    private fun StringBuilder.section(lines: List<String>) {
        appendLine()
        lines.forEach { appendLine(it) }
    }

    private fun row(label: String, value: String): String = label.padEnd(ROW_WIDTH) + value

    private fun hourText(hour: Int?): String = if (hour == null) "beyond day $LONG_HORIZON_DAYS" else "hour $hour"

    private fun clock(duration: Duration): String {
        val minutes = duration.inWholeMinutes
        return if (minutes < 60) "${minutes}m" else "${minutes / 60}h ${(minutes % 60).toString().padStart(2, '0')}m"
    }

    // Two decimals, by integer arithmetic. `core` is pure and compiles for Kotlin/Native as well as
    // the JVM, and a float here could render a different last digit on one target than the other —
    // which would make the golden fail on a platform rather than on a change.
    private fun ratio(numerator: Long, denominator: Long): String {
        if (denominator == 0L) return "-"
        val hundredths = numerator * 100 / denominator
        return "${hundredths / 100}.${(hundredths % 100).toString().padStart(2, '0')}"
    }

    private fun percent(part: Int, whole: Int): String {
        if (whole == 0) return "-"
        val hundredths = part.toLong() * 10_000 / whole
        return "${hundredths / 100}.${(hundredths % 100).toString().padStart(2, '0')}%"
    }

    private fun label(building: BuildingType): String = building.name.lowercase().replace('_', ' ')

    private fun label(technology: Technology): String = technology.name.lowercase()

    private fun label(technology: AdaptationTechnology): String = technology.name.lowercase()

    private fun label(axis: HostilityAxis): String = axis.name.lowercase()

    private val EPOCH: Instant = Instant.fromEpochMilliseconds(0)

    private const val ROW_WIDTH: Int = 50

    // Two weeks, because one is not long enough to show progression flattening and a month makes
    // this page slower than every other test in the module put together.
    private const val LONG_HORIZON_DAYS: Int = 14

    // Enough for a share to be stable to about a point; genesis walks its galaxy once per seed, so
    // this is the most expensive figure on the page.
    private const val BENCHMARK_SEEDS: Int = 100

    // The five a player actually buys in the opening; the Nanite Factory is behind Robotics 10.
    private val OPENING_PLAN = listOf(
        BuildingType.METAL_MINE,
        BuildingType.CRYSTAL_MINE,
        BuildingType.DEUTERIUM_SYNTHESIZER,
        BuildingType.SOLAR_PLANT,
        BuildingType.ROBOTICS_FACTORY,
    )
}
