package dev.fardavide.oltre.client.design.text

import dev.fardavide.oltre.core.AdaptationTechnology
import dev.fardavide.oltre.core.BuildingType
import dev.fardavide.oltre.core.EpithetAdjective
import dev.fardavide.oltre.core.EpithetNoun
import dev.fardavide.oltre.core.HostilityAxis
import dev.fardavide.oltre.core.ResourceKind
import dev.fardavide.oltre.core.ShipType
import dev.fardavide.oltre.core.StarClass
import dev.fardavide.oltre.core.Technology
import dev.fardavide.oltre.core.WorldEpithet
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

// **Every entry the catalogue can produce, resolved once.** The exhaustive `when` in `English`
// guarantees that each `StringId` has *a* branch; it cannot guarantee that the branch reads the
// arguments the `Strings` signature promised — `Arg.Count` read as `Arg.Number` is a cast that
// compiles and throws at the moment a player would have seen the sentence. This is what turns that
// into a test failure.
//
// The two assertions are the two halves of "the catalogue is whole":
//
// - **every entry says something**, resolved without throwing;
// - **every id is reachable**, so an id nobody can build is a dead branch rather than a promise.
//
// The arguments are placeholders on purpose. What is asserted is that a sentence *comes out*, not
// what it says — the words are pinned in `EnglishTest` and `ItalianTest`, which is where changing
// them should be a deliberate act.
//
// **Every language, not just the first.** The exhaustive `when` makes a missing branch a compile
// error, and this is what makes a *wrong* branch a test failure: `Italian` reads the same arguments
// from the same positions, and reading `Arg.Count` as `Arg.Number` throws here rather than on a
// player's screen. It is also the only thing standing behind the one entry Italian resolves by
// delegating to another — see `ShipsOfType` there.
class CatalogueTest {

    @Test
    fun `should give every entry words in every language`() {
        everyLanguage.forEach { language ->
            everyEntry.forEach { assertTrue(language.resolve(it).isNotEmpty(), "$language: $it") }
        }
    }

    // A `StringId` nothing can build is a branch in every language that no caller will ever reach.
    // The reverse — a `Strings` function naming an id — is already impossible to get wrong: it would
    // not compile.
    @Test
    fun `should make every id reachable through Strings`() {
        assertEquals(StringId.entries.toSet(), everyEntry.flatMap { it.ids() }.toSet())
    }

    // Recursive, because an entry can carry another as an argument and a joined run carries its own
    // separator — both of which are ids somebody has to have translated.
    private fun TextRes.ids(): List<StringId> = when (this) {
        is TextRes.Raw -> emptyList()
        is TextRes.Message -> listOf(id) + args.flatMap { (it as? Arg.Text)?.value?.ids().orEmpty() }
        is TextRes.Joined -> parts.flatMap { it.ids() } + separator.ids()
    }
}

// Every table there is. A language added without being listed here is a language nothing checks, so
// this is the one place a third one has to be remembered — and `translationsFor` is the other.
private val everyLanguage: List<Translations> = listOf(English, Italian)

// Generated by calling every function on `Strings` once, and once per enum constant where one is
// taken. It is long because the catalogue is long; that is the point of it.
private val everyEntry: List<TextRes> = buildList {
    add(Strings.clauses(listOf(TextRes("a"), TextRes("b"))))
    add(Strings.groupedNumber(3))
    add(Strings.signed(3))
    add(Strings.decimal(3, 3, false))
    add(Strings.durationMinutes(3))
    add(Strings.durationHoursMinutes(3, 3))
    add(Strings.durationHours(3))
    add(Strings.durationDaysHours(3, 3))
    add(Strings.countdown(3, 3, 3))
    add(Strings.watchedAt(3, 3))
    add(Strings.doneAt(3, 3))
    add(Strings.homeAt(3, 3))
    add(Strings.landsAt(3, 3))
    add(Strings.landedAt(3, 3))
    add(Strings.probeLandedAt(3, 3))
    add(Strings.levelBadge(3))
    add(Strings.sentences(listOf(TextRes("a"), TextRes("b"))))
    ResourceKind.entries.forEach { add(Strings.resourceName(it)) }
    ResourceKind.entries.forEach { add(Strings.resourceTitle(it)) }
    add(Strings.plainNumber(3))
    add(Strings.percent(3))
    add(Strings.perHour(TextRes("x")))
    add(Strings.plusPerHour(TextRes("x")))
    add(Strings.plusAmount(TextRes("x")))
    add(Strings.coordinate(3, 3, 3))
    ResourceKind.entries.forEach { add(Strings.amountOfResource(TextRes("x"), it)) }
    ResourceKind.entries.forEach { add(Strings.resourceReading(it, TextRes("x"))) }
    add(Strings.shipyardHeading())
    add(Strings.shipyardNotYetBuiltHeading())
    add(Strings.shipyardNote())
    add(Strings.hullsInFleet(3))
    add(Strings.shipsOwned(3))
    add(Strings.shipsIdle(3))
    add(Strings.shipsAway(3))
    add(Strings.shipsBuilding(3))
    add(Strings.shipsQueued(3))
    add(Strings.build())
    add(Strings.availableIn(TextRes("x")))
    add(Strings.availableNever())
    add(Strings.probeNeedsScout())
    add(Strings.scoutName())
    add(Strings.scoutPurpose())
    add(Strings.skiffName())
    add(Strings.skiffPurpose())
    add(Strings.haulerName())
    add(Strings.haulerPurpose())
    add(Strings.hazards(3))
    add(Strings.hazardsAtDistance(TextRes("x"), TextRes("x")))
    add(Strings.chartedUnsurveyed())
    add(Strings.dispatchUnsurveyedTitle())
    add(Strings.dispatchUnsurveyedNote(3, 3))
    add(Strings.dispatchProbeOffer(TextRes("x"), TextRes("x")))
    add(Strings.dispatchEverySkiffAwayTitle())
    ResourceKind.entries.forEach { add(Strings.dispatchAwayNote(3, TextRes("x"), TextRes("x"), it)) }
    add(Strings.dispatchAwayMore(3))
    add(Strings.dispatchAwayTail())
    add(Strings.dispatchNothingIdle())
    add(Strings.depositFull())
    add(Strings.depositEmpty())
    add(Strings.depositStock(TextRes("x"), TextRes("x")))
    add(Strings.richness(TextRes("x")))
    add(Strings.skiffCount(3))
    add(Strings.ofIdle(3))
    add(Strings.ladderNote(TextRes("x"), 3))
    add(Strings.rungNote(TextRes("x")))
    add(Strings.clampSubject(3))
    add(Strings.clampRestOrdinal(3))
    add(Strings.clampRestOthers(3))
    add(Strings.theWholeDeposit())
    add(Strings.eachShip(TextRes("x")))
    add(Strings.legOut(TextRes("x")))
    add(Strings.legOnStation(TextRes("x")))
    add(Strings.legStation(TextRes("x")))
    add(Strings.legWorking(TextRes("x")))
    add(Strings.legHome(TextRes("x")))
    add(Strings.dangerLevel(3))
    add(Strings.dangerNothingAdded())
    add(Strings.dangerBonus(3))
    add(Strings.yourOwnSystem())
    add(Strings.yourOwnSystemCapitalised())
    add(Strings.anotherGalaxy())
    add(Strings.unitsOut(TextRes("x")))
    add(Strings.bothDepositsEmpty())
    add(Strings.thisDepositEmpty())
    ResourceKind.entries.forEach { add(Strings.waitingAsk(TextRes("x"), TextRes("x"), TextRes("x"), it)) }
    add(Strings.waitingHoldsAgain(TextRes("x")))
    add(Strings.waitingNeverHolds())
    add(Strings.waitingRemedy())
    add(Strings.controlBringBack())
    add(Strings.controlSend())
    add(Strings.controlHomeIn())
    add(Strings.dispatchVerb())
    BuildingType.entries.forEach { add(Strings.buildingName(it)) }
    BuildingType.entries.forEach { add(Strings.buildingCompactName(it)) }
    ShipType.entries.forEach { add(Strings.shipName(it)) }
    ShipType.entries.forEach { add(Strings.shipsOfType(3, it)) }
    add(Strings.colonyFacilitiesHeading())
    add(Strings.powerHeading())
    add(Strings.energyEveryMineStopped())
    add(Strings.energyEveryMineAt(3))
    add(Strings.energyBreakEven())
    add(Strings.energyRoomForMineLevels(3))
    add(Strings.energyProduced(TextRes("x")))
    add(Strings.energyDrawn(TextRes("x")))
    add(Strings.energyShort(TextRes("x")))
    add(Strings.energySpare(TextRes("x")))
    add(Strings.onStationAt(TextRes("x")))
    add(Strings.fleetReturning())
    add(Strings.fromTarget(TextRes("x")))
    add(Strings.moreAway(3))
    add(Strings.powerSupply(TextRes("x")))
    add(Strings.powerDraw(TextRes("x")))
    add(Strings.solarFix(3, TextRes("x")))
    ResourceKind.entries.forEach { add(Strings.outputGain(TextRes("x"), it)) }
    add(Strings.backIn(TextRes("x")))
    add(Strings.suppliesMore(TextRes("x")))
    add(Strings.drawAlreadyCovered())
    add(Strings.throttlesEveryMine())
    add(Strings.solarPlantCovers(3))
    add(Strings.savedPerBuild(TextRes("x")))
    add(Strings.gateClause(3, TextRes("x")))
    add(Strings.gateSummaryNanite())
    add(Strings.gateSummaryAdaptationShort())
    add(Strings.gateSummaryAdaptationLong())
    add(Strings.gateSummaryResearchShort())
    add(Strings.gateSummaryResearchLong())
    add(Strings.gateFacilityLong(TextRes("x"), TextRes("x")))
    add(Strings.ladderStepHeld(TextRes("x")))
    add(Strings.naniteReliefLong(TextRes("x"), TextRes("x"), 3))
    add(Strings.naniteReliefShort(TextRes("x"), TextRes("x"), 3))
    add(Strings.requiresRobotics(3))
    add(Strings.becomesLevel(3))
    add(Strings.upgradeVerb())
    add(Strings.pointerLevelStep(3, 3, TextRes("x")))
    add(Strings.pointerBestBuy(3, TextRes("x")))
    add(Strings.sheetMineMakes())
    ResourceKind.entries.forEach { add(Strings.sheetMineAtLevel(it, 3)) }
    add(Strings.sheetFullStop())
    add(Strings.sheetPlantsSupply())
    add(Strings.sheetColonyDraws())
    add(Strings.sheetSoEveryMineAt())
    add(Strings.sheetThisLevelLifts())
    ResourceKind.entries.forEach { add(Strings.sheetRatherThanEnergy(it)) }
    add(Strings.sheetPaybackPrefix())
    add(Strings.sheetSupplyNotLimiting())
    add(Strings.sheetChangesNoRate())
    add(Strings.sheetPaysNextMineLevel())
    add(Strings.sheetPaysWhenDrawPasses())
    add(Strings.sheetMoreMineLevelAway())
    add(Strings.sheetMoreMineLevelsAway())
    add(Strings.sheetOneSpelled())
    add(Strings.sheetCannotPowerLevel())
    add(Strings.sheetPlantCarriesPrefix())
    add(Strings.sheetPlantCarriesSuffix())
    add(Strings.sheetShortensDeepBuild())
    add(Strings.sheetShortensEveryBuild())
    add(Strings.sheetNextBuildTakes(TextRes("x")))
    add(Strings.sheetAtBuildingLevelTakes(TextRes("x"), 3))
    add(Strings.sheetNaniteMineTakes(3))
    add(Strings.sheetNaniteUnaidedAt(3))
    add(Strings.sheetRoboticsIsAt())
    add(Strings.sheetLevelsToGo(3))
    add(Strings.sheetMetalSuffix())
    Technology.entries.forEach { add(Strings.technologyName(it)) }
    AdaptationTechnology.entries.forEach { add(Strings.adaptationName(it)) }
    Technology.entries.forEach { add(Strings.technologySubject(it)) }
    AdaptationTechnology.entries.forEach { add(Strings.adaptationUnit(it)) }
    BuildingType.entries.forEach { add(Strings.buildingShortName(it)) }
    add(Strings.researchHeading())
    add(Strings.adaptationHeading())
    add(Strings.ruleOneProjectAtATime())
    add(Strings.ruleOneLadderAtATime())
    add(Strings.ruleOneAtATime())
    add(Strings.researchVerb())
    add(Strings.verdictNothingThrottled())
    add(Strings.verdictNothingThrottledCompact())
    add(Strings.verdictNothingSurplus())
    add(Strings.verdictNothingSurplusCompact())
    add(Strings.haulGain(TextRes("x")))
    add(Strings.haulGainCompact(TextRes("x")))
    add(Strings.reachGain(TextRes("x"), TextRes("y")))
    add(Strings.reachGainCompact(TextRes("x")))
    add(Strings.plusPercent(3))
    add(Strings.toleranceBand(TextRes("x"), TextRes("x")))
    add(Strings.requires(TextRes("x")))
    add(Strings.namedLevel(TextRes("x"), 3))
    add(Strings.shortlistNothingVerb())
    add(Strings.shortlistNothing())
    add(Strings.shortlistVerb(3, 3))
    add(Strings.shortlist(3, 3))
    add(Strings.sheetSubjectPrefix(TextRes("x")))
    add(Strings.sheetArrow())
    add(Strings.sheetAtLevelOne())
    add(Strings.sheetToleranceSubject(TextRes("x")))
    add(Strings.sheetReachesNothing())
    add(Strings.sheetReachesPrefix())
    add(Strings.sheetReachesMiddle())
    add(Strings.sheetReachesSuffix())
    ResourceKind.entries.forEach { add(Strings.sheetAndWouldMake(it)) }
    add(Strings.sheetEachHullLifts())
    add(Strings.sheetAnHourOnStation())
    add(Strings.sheetPaysOnNextRun())
    add(Strings.sheetTheNextGalaxyIs())
    add(Strings.sheetAwayAndWouldBe())
    add(Strings.sheetPaysTheFurtherYouAim())
    add(Strings.sheetColonyDrawsAnd())
    add(Strings.sheetAtThatRatio(TextRes("x")))
    add(Strings.sheetRoundsAway())
    add(Strings.sheetPaysWhenPlantsCarry())
    add(Strings.sheetMultipliesSupply(TextRes("x")))
    add(Strings.sheetOutputDoesNotMove())
    add(Strings.sheetRequiresPrefix())
    ShipType.entries.forEach { add(Strings.ships(3, it)) }
    add(Strings.fleetsHeading())
    add(Strings.fleetsAwayOf(3, 3))
    add(Strings.fleetsNothingOut())
    add(Strings.workedHeading())
    add(Strings.workedNewestFirst())
    add(Strings.runCount(3))
    ResourceKind.entries.forEach { add(Strings.unrecordedRuns(3, TextRes("x"), it)) }
    add(Strings.depositFullWord())
    add(Strings.depositEmptyWord())
    add(Strings.worldRowPrefix(TextRes("x"), TextRes("x")))
    add(Strings.worldRowSeparator(TextRes("x")))
    add(Strings.galaxyLabel(3))
    add(Strings.galaxyNamed(3))
    add(Strings.galaxiesCount(3))
    add(Strings.systemsCount(TextRes("x")))
    add(Strings.surveyedCount(3))
    add(Strings.pinnedCount(3))
    add(Strings.nothingCharted())
    add(Strings.systemAddress(3, 3))
    add(Strings.relayEffect())
    add(Strings.dangerFromHere(3))
    add(Strings.reachSingle(TextRes("x")))
    add(Strings.reachRange(TextRes("x"), TextRes("x")))
    add(Strings.reachRangeMinutes(3, TextRes("x")))
    StarClass.entries.forEach { add(Strings.starClassName(it)) }
    StarClass.entries.forEach { add(Strings.starDetail(it, 3)) }
    StarClass.entries.forEach { add(Strings.starDetailCompact(it, 3)) }
    add(Strings.worldCount(3))
    add(Strings.worldsSurveyedCount(3))
    add(Strings.noWorlds())
    add(Strings.homeNote())
    add(Strings.probeLandsIn(TextRes("x")))
    add(Strings.probeFlight(TextRes("x")))
    add(Strings.probeFlightLabel(TextRes("x")))
    add(Strings.runFlight(TextRes("x")))
    add(Strings.nothingToSurvey(3))
    add(Strings.surveyedAtGenesis())
    add(Strings.dispatchProbe())
    add(Strings.dispatchProbeCompact())
    add(Strings.findSettleable(3))
    add(Strings.findNearMiss(3))
    add(Strings.findNone())
    add(Strings.temperatureReading(TextRes("x")))
    add(Strings.gravityReading(TextRes("x")))
    add(Strings.pressureReading(TextRes("x")))
    add(Strings.foundAgo(TextRes("x")))
    HostilityAxis.entries.forEach { add(Strings.axisName(it)) }
    // Every pair the galaxy can produce, rather than one of them: the adjective is inflected against
    // the noun in Italian, so a pair is where that can go wrong and a single sample would miss it.
    EpithetAdjective.entries.forEach { adjective ->
        EpithetNoun.entries.forEach { noun -> add(Strings.worldEpithet(WorldEpithet(adjective, noun))) }
    }
    add(Strings.noteHome())
    add(Strings.noteOccupied(TextRes("x")))
    add(Strings.noteSettleable())
    add(Strings.noteBarren(TextRes("x"), TextRes("x")))
    add(Strings.noteBarrenDiscovery())
    add(Strings.noteBlocked())
    add(Strings.noteWouldLandIt(TextRes("x"), 3))
    add(Strings.noteSurveyed())
    add(Strings.worthItAt(TextRes("x")))
    add(Strings.depositFraction(TextRes("x"), TextRes("x")))
    add(Strings.ledgerEmptyHeadline())
    add(Strings.ledgerEmptyDetail())
    add(Strings.ledgerNoMatchHeadline())
    add(Strings.ledgerNoMatchDetail())
    add(Strings.verdictWordHome())
    add(Strings.verdictWordOccupied())
    add(Strings.verdictWordBlocked())
    add(Strings.verdictWordBarren())
    add(Strings.verdictWordSettleable())
    add(Strings.discoveriesHeadingOne())
    add(Strings.discoveriesHeadingMany(3))
    add(Strings.pinnedHeading())
    add(Strings.relayLabel())
    add(Strings.ledgerModeWorlds())
    add(Strings.ledgerModeMap())
    add(Strings.searchPlaceholder())
    add(Strings.blockedAxisLine(TextRes("x"), TextRes("x"), TextRes("x")))
    add(Strings.middot())
    add(Strings.orbitSlot(3))
    add(Strings.tabColony())
    add(Strings.tabResearch())
    add(Strings.tabShipyard())
    add(Strings.tabGalaxy())
    add(Strings.tabFleets())
    add(Strings.stepperFewer())
    add(Strings.stepperMore())
    add(Strings.depositGap())
    add(Strings.notificationChannelName())
    add(Strings.notificationChannelDescription())
    add(Strings.watching(TextRes("x")))
    add(Strings.ratePerHour(TextRes("x")))
    ResourceKind.entries.forEach { add(Strings.resourceRailLabel(it)) }
    add(Strings.listed(listOf(TextRes("a"), TextRes("b"))))
    add(Strings.upgradesDoneTitle(3))
    add(Strings.upgradesDoneBody(TextRes("x")))
    add(Strings.reachedLevel(TextRes("x"), 3))
    add(Strings.buildCompleteBody())
    add(Strings.labFreeBody())
    add(Strings.adaptationOpenedBody())
    add(Strings.hullLeftYardTitle(TextRes("x")))
    add(Strings.hullLeftYardBody())
    add(Strings.probeReachedTitle(TextRes("x")))
    add(Strings.chartedNoneSettleable(3))
    add(Strings.chartedSettleable(3, 3))
    add(Strings.shipsHomeTitle())
    add(Strings.shipsHomeBody(TextRes("x")))
    add(Strings.affordableTitle(TextRes("x")))
    add(Strings.affordableBody(3))
    add(Strings.systemAddressBare(3, 3))
    BuildingType.entries.forEach { add(Strings.buildingFullName(it)) }
    ShipType.entries.forEach { add(Strings.shipTitleName(it)) }
    AdaptationTechnology.entries.forEach { add(Strings.adaptationFullName(it)) }
}
