#!/usr/bin/env bash
#
# Run Gradle against `:core` and `:sim` from a session that cannot resolve AGP.
#
# WHY THIS EXISTS
#
# The remote environment's egress policy answers 403 to `dl.google.com`, and every route to the
# Android Gradle Plugin ends there — `maven.google.com` redirects to it, the Gradle Plugin Portal
# redirects to Maven Central, and Google does not publish AGP to Maven Central. So the root
# `plugins {}` block cannot resolve and *every* Gradle invocation fails during configuration,
# including ones that touch no Android code at all.
#
# `:sim` depends only on `:core`, and it consumes `:core`'s **JVM** target. AGP is in `:core` only
# to publish an Android target that the sim never looks at. So a build restricted to those two
# modules, with the Android target dropped, compiles exactly the same `commonMain` sources and
# runs exactly the same harness. That is what this script does: it swaps in a minimal overlay for
# the three build files, runs Gradle, and always puts the real ones back.
#
# WHAT IT IS NOT
#
# Not a way to build the client. `client/*` is Compose and genuinely needs AGP, and a cloud session
# has no business writing UI anyway — see `.claude/rules/session-roles.md`. Not a fix for the
# blocked egress either; the real build files are untouched in git and CI builds the whole project
# normally. Nothing here should ever be committed into the actual build.
#
# USAGE
#
#   .claude/tools/gradle-without-agp.sh :sim:run
#   .claude/tools/gradle-without-agp.sh :core:jvmTest :sim:test
#   .claude/tools/gradle-without-agp.sh :core:jvmTest --tests '*BalanceCurveTest*'
#
set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO"

FILES=(settings.gradle.kts build.gradle.kts core/build.gradle.kts)

if [ $# -eq 0 ]; then
  echo "usage: $0 <gradle task> [more tasks/flags]" >&2
  echo "example: $0 :sim:run" >&2
  exit 2
fi

# Refuse to run against edited build files rather than restoring over the top of someone's work —
# the restore below is a hard `git checkout --`, which would discard them without asking. A tree
# left swapped by a killed run also lands here, which is the right place for it to stop.
if ! git diff --quiet -- "${FILES[@]}" || ! git diff --cached --quiet -- "${FILES[@]}"; then
  echo "error: these build files have uncommitted changes:" >&2
  git diff --name-only -- "${FILES[@]}" >&2
  git diff --cached --name-only -- "${FILES[@]}" >&2
  echo >&2
  echo "This script swaps them out and restores with 'git checkout --', which would discard" >&2
  echo "that work. Commit or stash it first. If a previous run was killed mid-flight, the" >&2
  echo "overlay may still be in place — 'git checkout -- ${FILES[*]}' puts the real ones back." >&2
  exit 1
fi

restore() { git checkout -- "${FILES[@]}"; }
trap restore EXIT INT TERM

cat > settings.gradle.kts <<'OVERLAY'
// OVERLAY — generated by .claude/tools/gradle-without-agp.sh, never committed.
rootProject.name = "oltre"
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

include(":core")
include(":sim")
OVERLAY

cat > build.gradle.kts <<'OVERLAY'
// OVERLAY — generated by .claude/tools/gradle-without-agp.sh, never committed.
plugins {
    alias(libs.plugins.kotlinJvm) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.kotlinxSerialization) apply false
}
OVERLAY

cat > core/build.gradle.kts <<'OVERLAY'
// OVERLAY — generated by .claude/tools/gradle-without-agp.sh, never committed.
// The real file also declares an Android target and the iOS ones; the sim consumes the JVM target,
// and `commonMain` is identical either way.
plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinxSerialization)
}

kotlin {
    jvmToolchain(21)

    jvm()

    sourceSets {
        commonMain.dependencies {
            api(libs.kotlinx.serialization.json)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}
OVERLAY

./gradlew "$@" --console=plain 2>&1 | grep -v "^Picked up JAVA_TOOL_OPTIONS"
exit "${PIPESTATUS[0]}"
